# Generated by Django 4.0.4 on 2022-10-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
