# Generated by Django 6.0.3 on 2026-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_customsetting_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='sender_email_prefix',
            field=models.CharField(blank=True, default='gregory', help_text="Local part of the sender email address (e.g. 'gregory' → gregory@site.domain).", max_length=64),
        ),
    ]
