# Generated by Django 6.0.4 on 2026-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_customsetting_sender_email_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='about_url',
            field=models.URLField(blank=True, default='', help_text='About page URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='api_domain',
            field=models.CharField(blank=True, default='', help_text='Domain where the Django backend is reachable (e.g. api.example.com). Used for unsubscribe links.', max_length=253),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='bluesky_url',
            field=models.URLField(blank=True, default='', help_text='Blue Sky profile URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='contact_url',
            field=models.URLField(blank=True, default='', help_text='Contact page URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='github_url',
            field=models.URLField(blank=True, default='', help_text='GitHub profile/repo URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='mastodon_url',
            field=models.URLField(blank=True, default='', help_text='Mastodon profile URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='support_url',
            field=models.URLField(blank=True, default='', help_text='Support page URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='Main website URL shown in the email footer (e.g. https://example.com).'),
        ),
    ]
