# Generated by Django 6.0.4 on 2026-04-18 13:26

import gregory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_customsetting_about_url_customsetting_api_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='postmark_api_token',
            field=gregory.models.EncryptedTextField(blank=True, help_text='Postmark API token for this site. Overrides the organisation-level token.', null=True),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='postmark_api_url',
            field=models.URLField(blank=True, default='https://api.postmarkapp.com/email', help_text='Postmark API URL for this site. Overrides the organisation-level URL.', null=True),
        ),
    ]
