# Generated by Django 6.0.4 on 2026-04-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_customsetting_about_url_customsetting_api_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='privacy_policy_url',
            field=models.URLField(blank=True, default='', help_text='Privacy policy page URL for the email footer.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='terms_url',
            field=models.URLField(blank=True, default='', help_text='Terms of service page URL for the email footer.'),
        ),
    ]
