# Generated by Django 6.0.4 on 2026-04-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0007_customsetting_privacy_policy_url_terms_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsetting',
            name='email_footer',
        ),
    ]
