# Generated by Django 6.0.6 on 2026-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0081_authors_authors_uorcid_gin_idx'),
        ('sitesettings', '0011_customsetting_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='generate_sitemap',
            field=models.BooleanField(default=False, help_text='Serve an XML sitemap for this site at /sitemap/sites/<site_id>/index.xml. Requires at least one sitemap subject below.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='sitemap_relevant_only',
            field=models.BooleanField(default=False, help_text="Only include articles marked relevant for at least one of the selected subjects (manual review or ML consensus, same semantics as the API's relevant=true filter)."),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='sitemap_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects whose articles appear in this site's sitemap. Choosing different subjects per site is how two sites backed by the same database avoid competing for the same articles in search engines.", related_name='sitemap_sites', to='gregory.subject'),
        ),
    ]
