# Generated by Django 6.0.6 on 2026-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0012_customsetting_generate_sitemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='has_author_pages',
            field=models.BooleanField(default=False, help_text='This site publishes author profile pages at /authors/<orcid>/. When enabled, author names in digest emails and the author RSS feed link to this site instead of orcid.org.'),
        ),
    ]
