# Generated by Django 6.0.6 on 2026-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0013_customsetting_has_author_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='citation',
            field=models.TextField(blank=True, default='', help_text="How to cite an export from this site. Leave blank to generate '{title}. Clinical trials export, {date}. {website_url}'."),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact address for this site, shown on exported files. Falls back to Admin email when blank.', max_length=254),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='data_license',
            field=models.CharField(blank=True, default='', help_text="Licence the exported data may be reused under (e.g. 'CC BY 4.0'). Distinct from Terms URL, which is the website's terms of service.", max_length=200),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='data_license_url',
            field=models.URLField(blank=True, default='', help_text='Link to the licence text referenced by Data licence.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='description',
            field=models.TextField(blank=True, default='', help_text="One paragraph describing what this project is. Shown on the 'About this file' sheet of exported workbooks."),
        ),
    ]
