# Generated by Django 6.0.6 on 2026-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0095_index_title_and_discovery_date_ordering_fields'),
        ('sitesettings', '0014_customsetting_about_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='sitemap_include_trials',
            field=models.BooleanField(default=False, help_text='Also list clinical trials for the selected subjects, at /sitemap/sites/<site_id>/trials.xml. Only enable this if the site actually publishes trial pages at /trials/<trial_id>/ — otherwise the sitemap would send crawlers to 404s.'),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='sitemap_relevant_only',
            field=models.BooleanField(default=False, help_text="Only include articles marked relevant for at least one of the selected subjects (manual review or ML consensus, same semantics as the API's relevant=true filter). Does not affect clinical trials, which carry no relevance judgement."),
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='sitemap_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects whose articles (and, when enabled below, clinical trials) appear in this site's sitemap. Choosing different subjects per site is how two sites backed by the same database avoid competing for the same content in search engines.", related_name='sitemap_sites', to='gregory.subject'),
        ),
    ]
