# Generated by Django 6.0.6 on 2026-09-05 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0015_customsetting_sitemap_include_trials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='sitemap_trial_statuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('not_yet_recruiting', 'Not yet recruiting'), ('recruiting', 'Recruiting'), ('enrolling_by_invitation', 'Enrolling by invitation'), ('active_not_recruiting', 'Active, not recruiting'), ('not_recruiting', 'Not recruiting'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=30), blank=True, default=list, help_text='Restrict the trials section to these recruitment statuses. Leave all unticked to list every trial for the selected subjects. Trials with no normalised status are excluded whenever a selection is made. Narrowing to the open/upcoming statuses is the usual way to keep the trials section from dwarfing the curated articles section.', verbose_name='Sitemap trial statuses'),
        ),
    ]
