# Generated by Django 6.0.6 on 2026-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0016_customsetting_sitemap_trial_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='sitemap_include_authors',
            field=models.BooleanField(default=False, help_text='Also list author profile pages for the selected subjects, at /sitemap/sites/<site_id>/authors.xml. Only enable this if the site actually publishes author pages at /authors/<orcid>/ — otherwise the sitemap would send crawlers to 404s.'),
        ),
    ]
