# Generated by Django 6.0.6 on 2026-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0096_team_api_listed'),
        ('sitesettings', '0017_customsetting_sitemap_include_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='api_public',
            field=models.BooleanField(default=False, help_text="When true, this site's scope_subjects are visible to anonymous API callers -- the union of every api_public site's scope is what an unauthenticated request can see. Defaults to False: a new site is private until someone deliberately publishes it. Replaces the organisation-level OrganizationApiSettings.make_api_public flag, which could not express one organisation owning both a public and a private site."),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='rss_enabled',
            field=models.BooleanField(default=False, help_text='When true, this site serves RSS feeds scoped to its scope_subjects, at /feed/sites/<site_id>/... . Matches the per-surface pattern of generate_sitemap: a site can serve an API without feeds, or the reverse. Defaults to False.'),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='scope_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects this site owns for anonymous API/RSS visibility. This defines what the site is allowed to publish -- it is distinct from sitemap_subjects (SEO curation, which should narrow within this scope, not define it). Seeded from sitemap_subjects at migration time as a starting value, not a rule -- the two are free to diverge from that point on. A subject left out of every site's scope is how internal/unpublished research stays private; there is no separate 'internal' flag.", related_name='scope_sites', to='gregory.subject'),
        ),
    ]
