# Generated by Django 6.0.6 on 2026-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0019_seed_site_visibility_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsetting',
            name='api_public',
            field=models.BooleanField(default=False, help_text="When true, this site's scope_subjects are visible to anonymous API callers -- the union of every api_public site's scope is what an unauthenticated request can see. Defaults to False: a new site is private until someone deliberately publishes it. Replaces the organisation-level OrganizationApiSettings.make_api_public flag for content visibility, which could not express one organisation owning both a public and a private site. That flag still governs /organizations/ and per-org serializer fields -- see its own docstring -- but no longer article/trial/RSS visibility."),
        ),
    ]
