# Generated by Django 6.0.6 on 2026-09-19 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('sitesettings', '0020_alter_customsetting_api_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='mcp_description',
            field=models.TextField(blank=True, default='', help_text="Optional. How the research assistant describes this instance to the model: its focus and framing. The model reads it, not people. If left blank, a description is generated from the site's name and subjects.", validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddField(
            model_name='customsetting',
            name='mcp_enabled',
            field=models.BooleanField(default=False, help_text="Offers this site's research assistant (MCP). Takes effect only when scope_subjects above is non-empty. The public MCP server only serves api_public sites, so on a private site this flag does nothing until authenticated MCP servers exist. Off by default: a site is not a tenant until someone decides it is."),
        ),
        migrations.CreateModel(
            name='SiteMcpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Served at gregory-ai://doc/{slug} from a later release. Unique per site.', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain text')], default='text/markdown', max_length=50)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are kept but never published.')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_documents', to='sites.site')),
            ],
            options={
                'ordering': ['ordering', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='sitemcpdocument_site_slug_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SiteMcpPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The MCP prompt name. Unique per site.', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('template', models.TextField(help_text='string.Template syntax: $topic or ${topic} for an argument, and $$ for a literal dollar sign.', validators=[django.core.validators.MaxLengthValidator(8000)])),
                ('arguments', models.JSONField(blank=True, default=list, help_text='[{"name": "topic", "description": "…", "required": true}]')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are kept but never published.')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_prompts', to='sites.site')),
            ],
            options={
                'ordering': ['ordering', 'name'],
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='sitemcpprompt_site_name_uniq')],
            },
        ),
    ]
