# Generated by Django 6.0.6 on 2026-09-20 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0022_seed_default_mcp_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsetting',
            name='mcp_description',
            field=models.TextField(blank=True, default='', help_text="Optional. How the research assistant describes this instance to the model: its focus and framing. The model reads it, not people — it becomes the first paragraph of the assistant's generated instructions. A blank value generates that introduction from the site's name and subjects instead.", validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='sitemcpdocument',
            name='slug',
            field=models.SlugField(help_text='Served at gregory-ai://doc/{slug}. Unique per site.', max_length=64),
        ),
    ]
