# Generated by Django 6.0.6 on 2026-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("sitesettings", "0023_alter_customsetting_mcp_description_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="customsetting",
			name="mcp_enabled",
			field=models.BooleanField(
				default=False,
				help_text="Offers this site's research assistant (MCP). Takes effect only when scope_subjects above is non-empty. The anonymous MCP address only serves api_public sites; a private site with this flag is served at its editor address, to the people granted editor access below. Off by default: a site is not a tenant until someone decides it is.",
			),
		),
	]
