# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
# COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install Django==4.0.3
RUN pip install psycopg2-binary
# RUN pip install -r requirements.txt
# COPY django /code/
ADD django /code/