# Generated by Django 4.0.4 on 2022-11-06 11:15

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=api.models.generateRandomAPIKey, max_length=64, unique=True)),
                ('client_name', models.CharField(default='Client Name', max_length=200)),
                ('client_contacts', models.CharField(default='client@contact.com', max_length=200)),
                ('ip_addresses', models.CharField(blank=True, max_length=500)),
                ('begin_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=api.models.oneYearFromToday)),
                ('max_calls_minute', models.IntegerField(default=60)),
                ('max_calls_hour', models.IntegerField(default=3600)),
                ('max_calls_day', models.IntegerField(default=86400)),
            ],
        ),
        migrations.CreateModel(
            name='APIAccessSchemeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(default='GET /', max_length=200)),
                ('ip_addr', models.CharField(blank=True, max_length=20, null=True)),
                ('access_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('http_code', models.IntegerField(blank=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('api_access_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apiaccessscheme')),
            ],
        ),
    ]
