# Generated by Django 4.0.4 on 2022-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccessschemelog',
            name='payload_received',
            field=models.CharField(blank=True, max_length=1700, null=True),
        ),
    ]
