# Generated by Django 6.0.6 on 2026-07-12 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiaccessscheme_organization_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessschemelog',
            name='access_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
