# Generated by Django 6.0.6 on 2026-07-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_apiaccessschemelog_access_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessschemelog',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
