# Generated by Django 6.0.6 on 2026-09-09 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apiaccessschemelog_ip_addr'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccessscheme',
            name='site',
            field=models.ForeignKey(blank=True, help_text="The site this API key is bound to. A key grants exactly that site's scope_subjects, whether or not the site is api_public -- this is how a private site's own frontend authenticates to read its own scope. Existing keys are backfilled by data migration from their organisation's default OrganizationSite (is_default=True); an organisation with no default site cannot be backfilled and the migration raises rather than guessing, since a key mapped to nothing is a dead frontend.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_access_schemes', to='sites.site'),
        ),
    ]
