# Generated by Django 6.0.6 on 2026-10-03 16:48

import django.db.models.deletion
import oauth2_provider.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		("sites", "0002_alter_domain_unique"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="IDToken",
			fields=[
				("id", models.BigAutoField(primary_key=True, serialize=False)),
				(
					"jti",
					models.UUIDField(
						default=uuid.uuid4,
						editable=False,
						unique=True,
						verbose_name="JWT Token ID",
					),
				),
				("expires", models.DateTimeField(verbose_name="expires")),
				("scope", models.TextField(blank=True, verbose_name="scope")),
				(
					"created",
					models.DateTimeField(auto_now_add=True, verbose_name="created"),
				),
				(
					"updated",
					models.DateTimeField(auto_now=True, verbose_name="updated"),
				),
				(
					"application",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
						verbose_name="application",
					),
				),
				(
					"user",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="%(app_label)s_%(class)s",
						to=settings.AUTH_USER_MODEL,
						verbose_name="user",
					),
				),
			],
			options={
				"abstract": False,
			},
		),
		migrations.CreateModel(
			name="AccessToken",
			fields=[
				("id", models.BigAutoField(primary_key=True, serialize=False)),
				("token", models.TextField(verbose_name="token")),
				(
					"token_checksum",
					oauth2_provider.models.TokenChecksumField(
						db_index=True,
						max_length=64,
						unique=True,
						verbose_name="token checksum",
					),
				),
				("expires", models.DateTimeField(verbose_name="expires")),
				("scope", models.TextField(blank=True, verbose_name="scope")),
				(
					"resource",
					oauth2_provider.models.ResourceJSONField(
						blank=True, default=list, verbose_name="resource"
					),
				),
				(
					"created",
					models.DateTimeField(auto_now_add=True, verbose_name="created"),
				),
				(
					"updated",
					models.DateTimeField(auto_now=True, verbose_name="updated"),
				),
				(
					"tier",
					models.CharField(
						blank=True,
						choices=[("editor", "Editor"), ("public", "Public")],
						max_length=10,
					),
				),
				(
					"application",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
						verbose_name="application",
					),
				),
				(
					"site",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="+",
						to="sites.site",
					),
				),
				(
					"user",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="%(app_label)s_%(class)s",
						to=settings.AUTH_USER_MODEL,
						verbose_name="user",
					),
				),
				(
					"id_token",
					models.OneToOneField(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="access_token",
						to=settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL,
						verbose_name="ID token",
					),
				),
			],
			options={
				"abstract": False,
			},
		),
		migrations.CreateModel(
			name="RefreshToken",
			fields=[
				("id", models.BigAutoField(primary_key=True, serialize=False)),
				("token", models.TextField(verbose_name="token")),
				(
					"token_checksum",
					oauth2_provider.models.TokenChecksumField(
						max_length=64, verbose_name="token checksum"
					),
				),
				(
					"token_family",
					models.UUIDField(
						blank=True,
						editable=False,
						null=True,
						verbose_name="token family",
					),
				),
				(
					"resource",
					oauth2_provider.models.ResourceJSONField(
						blank=True, default=list, verbose_name="resource"
					),
				),
				(
					"created",
					models.DateTimeField(auto_now_add=True, verbose_name="created"),
				),
				(
					"updated",
					models.DateTimeField(auto_now=True, verbose_name="updated"),
				),
				("revoked", models.DateTimeField(null=True, verbose_name="revoked")),
				(
					"access_token",
					models.OneToOneField(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="refresh_token",
						to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
						verbose_name="access token",
					),
				),
				(
					"application",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
						verbose_name="application",
					),
				),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="%(app_label)s_%(class)s",
						to=settings.AUTH_USER_MODEL,
						verbose_name="user",
					),
				),
			],
			options={
				"abstract": False,
			},
		),
		migrations.AddField(
			model_name="accesstoken",
			name="source_refresh_token",
			field=models.OneToOneField(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="refreshed_access_token",
				to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL,
				verbose_name="source refresh token",
			),
		),
		migrations.CreateModel(
			name="SiteEditor",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"can_edit",
					models.BooleanField(
						default=True,
						help_text="Untick for read-only access: the editor read scope without the edit tools. Saving this unticked ends the person's existing edit sessions on this site.",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("revoked_at", models.DateTimeField(blank=True, null=True)),
				(
					"granted_by",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"site",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="editor_grants",
						to="sites.site",
					),
				),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="site_editor_grants",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"verbose_name": "site editor",
				"verbose_name_plural": "site editors",
			},
		),
		migrations.AddIndex(
			model_name="refreshtoken",
			index=models.Index(
				fields=["token_family"], name="mcpauth_ref_token_f_8a130f_idx"
			),
		),
		migrations.AlterUniqueTogether(
			name="refreshtoken",
			unique_together={("token_checksum", "revoked")},
		),
		migrations.AddConstraint(
			model_name="siteeditor",
			constraint=models.UniqueConstraint(
				condition=models.Q(("revoked_at__isnull", True)),
				fields=("user", "site"),
				name="unique_active_site_editor",
			),
		),
	]
