# Generated by Django 4.0.3 on 2022-03-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.TextField()),
                ('label', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'entities',
                'db_table': 'entities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('language', models.TextField()),
                ('subject', models.TextField()),
                ('method', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'sources',
                'db_table': 'sources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('discovery_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('relevant', models.BooleanField(blank=True, null=True)),
                ('sent', models.BooleanField(blank=True, null=True)),
                ('sent_to_twitter', models.BooleanField(blank=True, null=True)),
                ('sent_to_subscribers', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'trials',
                'db_table': 'trials',
                'managed': True,
                'unique_together': {('title', 'link')},
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('relevant', models.BooleanField(blank=True, null=True)),
                ('ml_prediction_gnb', models.BooleanField(blank=True, null=True)),
                ('ml_prediction_lr', models.BooleanField(blank=True, null=True)),
                ('discovery_date', models.DateTimeField()),
                ('noun_phrases', models.JSONField(blank=True, null=True)),
                ('sent_to_admin', models.BooleanField(blank=True, null=True)),
                ('sent_to_subscribers', models.BooleanField(blank=True, null=True)),
                ('sent_to_twitter', models.BooleanField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='gregory.categories')),
                ('entities', models.ManyToManyField(to='gregory.entities')),
                ('source', models.ForeignKey(blank=True, db_column='source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gregory.sources')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'db_table': 'articles',
                'managed': True,
                'unique_together': {('title', 'link')},
            },
        ),
    ]
