# Generated by Django 4.0.3 on 2022-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
