# Generated by Django 5.2.1 on 2025-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrunlog',
            name='algorithm',
            field=models.CharField(choices=[('pubmed_bert', 'PubMed BERT'), ('lgbm_tfidf', 'LGBM TF-IDF'), ('lstm', 'LSTM'), ('unknown', 'Unknown')], default='unknown', help_text='ML algorithm used for the run', max_length=20),
        ),
    ]
