# Generated by Django 5.1.5 on 2025-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0002_predictionrunlog_algorithm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlpredictions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mlpredictions',
            name='algorithm',
            field=models.CharField(choices=[('pubmed_bert', 'PubMed BERT'), ('lgbm_tfidf', 'LGBM TF-IDF'), ('lstm', 'LSTM'), ('unknown', 'Unknown')], default='unknown', help_text='ML algorithm used for prediction', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='auto_predict',
            field=models.BooleanField(default=False, help_text='Enable automatic ML prediction for new articles'),
        ),
        migrations.AlterUniqueTogether(
            name='mlpredictions',
            unique_together={('article', 'subject', 'model_version', 'algorithm')},
        ),
    ]
