# Generated by Django 4.0.3 on 2022-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0003_alter_articles_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trials',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
