# Generated by Django 5.1.5 on 2025-06-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0004_update_articlesubjectrelevance_allow_null'),
    ]

    operations = [
        # Fix subjects table foreign key constraint
        migrations.RunSQL(
            sql="""
            -- Safely drop any foreign key constraints on subjects.team_id pointing to organizations_organization
            DO $$
            DECLARE
                constraint_record RECORD;
            BEGIN
                FOR constraint_record IN 
                    SELECT tc.constraint_name
                    FROM information_schema.table_constraints tc
                    JOIN information_schema.constraint_column_usage ccu 
                        ON tc.constraint_name = ccu.constraint_name
                    WHERE tc.constraint_type = 'FOREIGN KEY'
                        AND tc.table_name = 'subjects'
                        AND ccu.table_name = 'organizations_organization'
                        AND tc.constraint_name LIKE '%team_id%'
                LOOP
                    EXECUTE 'ALTER TABLE subjects DROP CONSTRAINT IF EXISTS ' || constraint_record.constraint_name;
                END LOOP;
            END
            $$;
            """,
            reverse_sql="-- Note: Cannot reverse dynamically dropped constraints"
        ),
        
        # Update the subjects.team field to point to the correct table
        migrations.AlterField(
            model_name='subject',
            name='team',
            field=models.ForeignKey(
                null=True, 
                blank=False, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='subjects', 
                to='gregory.team'
            ),
        ),
        
        # Ensure the correct foreign key constraint exists for subjects
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE constraint_name = 'subjects_team_id_fk_gregory_team'
                    AND table_name = 'subjects'
                ) THEN
                    ALTER TABLE subjects 
                    ADD CONSTRAINT subjects_team_id_fk_gregory_team 
                    FOREIGN KEY (team_id) 
                    REFERENCES gregory_team(id) 
                    ON DELETE CASCADE;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            ALTER TABLE subjects 
            DROP CONSTRAINT IF EXISTS subjects_team_id_fk_gregory_team;
            """
        ),
        
        # Fix sources table foreign key constraint
        migrations.RunSQL(
            sql="""
            -- Safely drop any foreign key constraints on sources.team_id pointing to organizations_organization
            DO $$
            DECLARE
                constraint_record RECORD;
            BEGIN
                FOR constraint_record IN 
                    SELECT tc.constraint_name
                    FROM information_schema.table_constraints tc
                    JOIN information_schema.constraint_column_usage ccu 
                        ON tc.constraint_name = ccu.constraint_name
                    WHERE tc.constraint_type = 'FOREIGN KEY'
                        AND tc.table_name = 'sources'
                        AND ccu.table_name = 'organizations_organization'
                        AND tc.constraint_name LIKE '%team_id%'
                LOOP
                    EXECUTE 'ALTER TABLE sources DROP CONSTRAINT IF EXISTS ' || constraint_record.constraint_name;
                END LOOP;
            END
            $$;
            
            -- Add correct foreign key constraint for sources
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE constraint_name = 'sources_team_id_fk_gregory_team'
                    AND table_name = 'sources'
                ) THEN
                    ALTER TABLE sources 
                    ADD CONSTRAINT sources_team_id_fk_gregory_team 
                    FOREIGN KEY (team_id) 
                    REFERENCES gregory_team(id) 
                    ON DELETE CASCADE;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            ALTER TABLE sources 
            DROP CONSTRAINT IF EXISTS sources_team_id_fk_gregory_team;
            """
        ),
    ]
