# Generated by Django 4.0.3 on 2022-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0004_alter_trials_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='source_for',
            field=models.CharField(choices=[('articles', 'Articles'), ('trials', 'Trials')], default='articles', max_length=50),
        ),
    ]
