# Generated by Django 4.0.3 on 2022-03-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0005_sources_source_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trials',
            name='source',
            field=models.ForeignKey(blank=True, db_column='source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gregory.sources'),
        ),
    ]
