# Generated by Django 4.0.3 on 2022-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0006_alter_trials_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
