# Generated by Django 5.1.5 on 2025-06-02 20:03

from django.db import migrations


def update_team_names(apps, schema_editor):
    """Update existing teams to have meaningful names based on their organization"""
    Team = apps.get_model('gregory', 'Team')
    
    for team in Team.objects.all():
        if team.name == 'team-default-name' and team.organization:
            # Set the team name to be the organization name initially
            # This maintains backwards compatibility
            team.name = team.organization.name
            team.save()


def reverse_update_team_names(apps, schema_editor):
    """Reverse the team name updates"""
    Team = apps.get_model('gregory', 'Team')
    
    for team in Team.objects.all():
        team.name = 'team-default-name'
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0007_add_team_name_field_with_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(update_team_names, reverse_update_team_names),
    ]
