# Generated by Django 4.0.3 on 2022-03-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0008_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.URLField(default='DELETE', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(default='delete'),
            preserve_default=False,
        ),
    ]
