# Generated by Django 4.0.3 on 2022-03-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0009_alter_articles_link_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trials',
            name='link',
            field=models.URLField(default='delete', max_length=2000),
            preserve_default=False,
        ),
    ]
