# Generated by Django 5.1.5 on 2025-06-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0009_fix_articles_teams_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='keyword_filter',
            field=models.TextField(blank=True, help_text='Keywords to filter articles. Use comma-separated values for multiple keywords, or quoted strings for exact phrases (e.g., "multiple sclerosis", alzheimer, parkinson). Only applies to certain feed sources like bioRxiv and medRxiv.', null=True),
        ),
    ]
