# Generated by Django 4.0.3 on 2022-03-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0010_alter_trials_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entities',
            unique_together={('entity', 'label')},
        ),
    ]
