# Generated by Django 5.1.5 on 2025-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0010_add_keyword_filter_to_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='language',
            field=models.CharField(blank=True, null=True),
        ),
    ]
