# Generated by Django 4.0.3 on 2022-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0010_alter_trials_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
