# Generated by Django 4.0.3 on 2022-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0011_alter_articles_unique_together_alter_articles_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trials',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trials',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
