# Generated by Django 4.0.3 on 2022-03-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0012_alter_trials_unique_together_alter_trials_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='doi',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
