# Generated by Django 5.2.3 on 2025-06-16 15:40
"""
This migration alters the unique constraints on various models in the Gregory app.
It was created because we previously configured the models unique_together setting, which was deprecated.
It can be safely faked if needed.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0012_alter_sources_keyword_filter_articletrialreference'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='articlesubjectrelevance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='articletrialreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mlpredictions',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teamcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='articles',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='unique_article_title_link'),
        ),
        migrations.AddConstraint(
            model_name='articlesubjectrelevance',
            constraint=models.UniqueConstraint(fields=('article', 'subject'), name='unique_article_subject_relevance'),
        ),
        migrations.AddConstraint(
            model_name='articletrialreference',
            constraint=models.UniqueConstraint(fields=('article', 'trial', 'identifier_type'), name='unique_article_trial_identifier'),
        ),
        migrations.AddConstraint(
            model_name='mlpredictions',
            constraint=models.UniqueConstraint(fields=('article', 'subject', 'model_version', 'algorithm'), name='unique_article_subject_prediction'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('team', 'subject_slug'), name='unique_team_subject_slug'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organization_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teamcategory',
            constraint=models.UniqueConstraint(fields=('team', 'category_slug'), name='unique_team_category_slug'),
        ),
    ]
