# Generated by Django 5.2.3 on 2025-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0013_alter_articles_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='keyword_filter',
            field=models.TextField(blank=True, help_text='Keywords to filter articles. Use comma-separated values for multiple keywords, or quoted strings for exact phrases (e.g., "multiple sclerosis", alzheimer, parkinson). Applies to supported feed sources like bioRxiv and PNAS.', null=True),
        ),
    ]
