# Generated by Django 4.0.4 on 2022-07-31 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0013_articles_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=150)),
                ('given_name', models.CharField(max_length=150)),
                ('ORCID', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'authors',
                'db_table': 'authors',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='kind',
            field=models.CharField(choices=[('science paper', 'Science Paper'), ('news article', 'News Article')], default='science paper', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='Terms to include in category (comma separated)'),
        ),
        migrations.AddField(
            model_name='trials',
            name='categories',
            field=models.ManyToManyField(to='gregory.categories'),
        ),
        migrations.AddField(
            model_name='trials',
            name='sent_real_time_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='sent_to_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='discovery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_for',
            field=models.CharField(choices=[('science paper', 'Science Paper'), ('trials', 'Trials'), ('news article', 'News Article')], default='science paper', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='authors',
            field=models.ManyToManyField(blank=True, to='gregory.authors'),
        ),
    ]
