# Generated by Django 4.0.4 on 2022-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0014_authors_articles_kind_categories_category_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='ignore_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
