# Generated by Django 5.2.3 on 2025-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0015_remove_mlpredictions_gnb_remove_mlpredictions_lr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated from given_name and family_name', max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated from given_name and family_name', max_length=301, null=True),
        ),
    ]
