# Generated by Django 5.2.3 on 2025-07-12 10:09

from django.db import migrations


def populate_full_name(apps, schema_editor):
    """
    Populate the full_name field for existing authors by combining given_name and family_name.
    """
    Authors = apps.get_model('gregory', 'Authors')
    
    # Update all authors with empty full_name field
    authors_to_update = []
    for author in Authors.objects.filter(full_name__isnull=True):
        author.full_name = f"{author.given_name} {author.family_name}".strip()
        authors_to_update.append(author)
    
    # Bulk update for better performance
    if authors_to_update:
        Authors.objects.bulk_update(authors_to_update, ['full_name'], batch_size=1000)
        print(f"Updated {len(authors_to_update)} authors with full_name field")


def reverse_populate_full_name(apps, schema_editor):
    """
    Reverse migration: clear the full_name field.
    """
    Authors = apps.get_model('gregory', 'Authors')
    Authors.objects.update(full_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0016_add_full_name_field_to_authors'),
    ]

    operations = [
        migrations.RunPython(
            populate_full_name,
            reverse_populate_full_name,
        ),
    ]
