# Generated by Django 5.2.3 on 2025-07-13 12:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0017_populate_full_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='usummary',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('summary'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='articles',
            name='utitle',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('title'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='usummary',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('summary'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='utitle',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('title'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='usummary',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('summary'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='utitle',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('title'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='trials',
            name='usummary',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('summary'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='trials',
            name='utitle',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('title'), output_field=models.TextField()),
        ),
    ]
