# Generated by Django 5.2.3 on 2025-07-13 14:46

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0018_add_uppercase_helper_columns_to_trials_articles'),
    ]

    operations = [
        TrigramExtension(),
    ]
