# Generated by Django 4.0.4 on 2022-08-05 20:28
# from gregory.models import Sources, Subject
from django.db import migrations

def link_subjects(apps, schema_editor):
	Source = apps.get_model('gregory', 'Sources')
	Subject = apps.get_model('gregory', 'Subject')
	for source in Source.objects.all():
		subject, created = Subject.objects.get_or_create(subject_name=source.subject)
		source.subject_link = subject
		source.save()

class Migration(migrations.Migration):

	dependencies = [
		('gregory', '0020_alter_sources_subject_link'),
	]

	operations = [ migrations.RunPython(link_subjects),
	]
