# Generated by Django 5.2.3 on 2025-07-13 16:38

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0020_add_gin_indexes_for_text_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='ufull_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('full_name'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='ufull_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('full_name'), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='authors',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ufull_name'], name='authors_ufull_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
