# Generated by Django 5.2.3 on 2025-07-13 14:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0020_enable_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articles',
            index=django.contrib.postgres.indexes.GinIndex(fields=['utitle'], name='articles_utitle_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=django.contrib.postgres.indexes.GinIndex(fields=['usummary'], name='articles_usummary_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=django.contrib.postgres.indexes.GinIndex(fields=['utitle'], name='trials_utitle_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=django.contrib.postgres.indexes.GinIndex(fields=['usummary'], name='trials_usummary_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
