# Generated by Django 4.0.4 on 2022-08-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0021_transfer_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='subject',
        ),
    ]
