# Generated by Django 5.2.3 on 2025-07-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0022_add_category_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='sent_to_subscribers',
        ),
        migrations.RemoveField(
            model_name='historicalarticles',
            name='sent_to_subscribers',
        ),
    ]
