# Generated by Django 5.2.3 on 2025-07-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0023_remove_articles_sent_to_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='relevant',
        ),
        migrations.RemoveField(
            model_name='historicalarticles',
            name='relevant',
        ),
        migrations.RemoveField(
            model_name='historicaltrials',
            name='relevant',
        ),
        migrations.RemoveField(
            model_name='trials',
            name='relevant',
        ),
    ]
