# Generated by Django 4.0.4 on 2022-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0023_rename_subject_link_sources_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='access',
            field=models.CharField(choices=[('unknown','Unknown'),('open', 'Open'), ('restricted', 'Restricted')], default='unkown', max_length=50),
        ),
    ]
