# Generated by Django 4.0.4 on 2022-09-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0024_articles_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_in',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
