# Generated by Django 6.0 on 2025-12-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0026_normalize_orcid_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticles',
            name='crossref_check',
        ),
        migrations.RemoveField(
            model_name='historicalarticles',
            name='usummary',
        ),
        migrations.RemoveField(
            model_name='historicalarticles',
            name='utitle',
        ),
        migrations.DeleteModel(
            name='HistoricalAuthors',
        ),
    ]
