# Generated by Django 4.0.4 on 2022-09-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0027_rename_published_in_articles_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='container_title',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
