# Generated by Django 6.0 on 2025-12-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0027_remove_historicalarticles_crossref_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='method',
            field=models.CharField(choices=[('rss', 'RSS'), ('scrape', 'Scrape'), ('manual', 'Manual submission'), ('ctgov_api', 'ClinicalTrials.gov API')], default='rss', max_length=10),
        ),
    ]
