# Generated by Django 6.0 on 2025-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0028_add_ctgov_api_source_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='ctgov_search_query',
            field=models.TextField(blank=True, help_text='Search query for ClinicalTrials.gov API. Enter conditions/diseases to search (e.g., "multiple sclerosis"). Only used when method is "ClinicalTrials.gov API".', null=True, verbose_name='ClinicalTrials.gov Search Query'),
        ),
    ]
