# Generated by Django 4.0.4 on 2022-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0028_articles_container_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='access',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('restricted', 'Restricted')], default='unknown', max_length=50, null=True),
        ),
    ]
