# Generated by Django 6.0 on 2025-12-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0029_add_ctgov_search_query_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='ctgov_search_query',
        ),
        migrations.AddField(
            model_name='sources',
            name='ctgov_search_condition',
            field=models.TextField(blank=True, help_text='Search condition/Disease for ClinicalTrials.gov API. Enter conditions/diseases to search (e.g., "multiple sclerosis"). Only used when method is "ClinicalTrials.gov API".', null=True, verbose_name='ClinicalTrials.gov Search condition/Disease'),
        ),
    ]
