# Generated by Django 6.0 on 2025-12-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0030_remove_sources_ctgov_search_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='ctg_detailed_description',
            field=models.TextField(blank=True, help_text='Detailed description from ClinicalTrials.gov API', null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='ctg_detailed_description',
            field=models.TextField(blank=True, help_text='Detailed description from ClinicalTrials.gov API', null=True),
        ),
    ]
