# Generated by Django 6.0.3 on 2026-04-16 17:41

import django.db.models.deletion
import gregory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0031_add_ctg_detailed_description'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postmark_api_token', gregory.models.EncryptedTextField(blank=True, help_text='Postmark API Token for this organization.', null=True)),
                ('postmark_api_url', models.URLField(blank=True, help_text='Postmark API URL for this organization.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(help_text='The organization associated with these credentials.', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Credential',
                'verbose_name_plural': 'Organization Credentials',
            },
        ),
    ]
