# Generated by Django 6.0.3 on 2026-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0032_organizationcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcredentials',
            name='postmark_api_url',
            field=models.URLField(blank=True, default='https://api.postmarkapp.com/email', help_text='Postmark API URL for this organization.', null=True),
        ),
        migrations.AlterField(
            model_name='teamcredentials',
            name='postmark_api_url',
            field=models.URLField(blank=True, default='https://api.postmarkapp.com/email', help_text='Postmark API URL for this team.', null=True),
        ),
    ]
