# Generated by Django 5.2 on 2025-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0033_remove_trials_categories_team_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcategory',
            name='subjects',
            field=models.ManyToManyField(related_name='team_subjects', to='gregory.subject'),
        ),
    ]
