# Generated by Django 6.0.3 on 2026-04-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0033_alter_organizationcredentials_postmark_api_url_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The website (Site) this team sends emails from. Overrides the global SITE_ID setting.', null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
