# Generated by Django 6.0.3 on 2026-04-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0034_team_site'),
        ('organizations', '0006_alter_organization_slug'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Mark this as the default site for the organization. Used when a team has no site configured.')),
                ('organization', models.ForeignKey(help_text='The organization this site belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_sites', to='organizations.organization')),
                ('site', models.ForeignKey(help_text='The Django site associated with this organization.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_sites', to='sites.site')),
            ],
            options={
                'verbose_name': 'Organization Site',
                'verbose_name_plural': 'Organization Sites',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='unique_default_site_per_organization')],
                'unique_together': {('organization', 'site')},
            },
        ),
    ]
