# Generated by Django 5.2 on 2025-05-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0035_convert_team_to_concrete_model'),
    ]

    operations = [
    ]
