# Generated by Django 6.0.3 on 2026-04-16 19:15

import gregory.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0035_organizationsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcredentials',
            name='orcid_client_id',
            field=gregory.models.EncryptedTextField(blank=True, help_text='ORCID Client ID for this organization.', null=True),
        ),
        migrations.AddField(
            model_name='organizationcredentials',
            name='orcid_client_secret',
            field=gregory.models.EncryptedTextField(blank=True, help_text='ORCID Client Secret for this organization.', null=True),
        ),
        migrations.AddField(
            model_name='teamcredentials',
            name='orcid_client_id',
            field=gregory.models.EncryptedTextField(blank=True, help_text='ORCID Client ID for this team.', null=True),
        ),
        migrations.AddField(
            model_name='teamcredentials',
            name='orcid_client_secret',
            field=gregory.models.EncryptedTextField(blank=True, help_text='ORCID Client Secret for this team.', null=True),
        ),
    ]
