# Generated by Django 6.0.3 on 2026-04-17 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0037_fix_stale_team_fk_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this team.', related_name='teams_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
