# Generated by Django 6.0.3 on 2026-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0038_add_team_members_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive teams are soft-deleted: their data is preserved and can be reassigned to another team.'),
        ),
    ]
