# Generated by Django 6.0.4 on 2026-04-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0039_add_team_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamCredentials',
        ),
    ]
