# Generated by Django 6.0.4 on 2026-04-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0040_remove_teamcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gregory.subject'),
        ),
    ]
