# Generated by Django 6.0.4 on 2026-05-03 14:52

import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0041_alter_sources_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAuthors',
            fields=[
                ('author_id', models.IntegerField(blank=True, db_index=True)),
                ('family_name', models.CharField(max_length=150)),
                ('given_name', models.CharField(max_length=150)),
                ('full_name', models.CharField(blank=True, db_index=True, help_text='Auto-generated from given_name and family_name', max_length=301, null=True)),
                ('ORCID', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('orcid_check', models.DateTimeField(blank=True, null=True)),
                ('ufull_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('full_name'), output_field=models.TextField())),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical authors',
                'verbose_name_plural': 'historical authors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
