# Generated by Django 6.0.4 on 2026-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0043_organizationapisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
