# Generated by Django 6.0.4 on 2026-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0045_historicalarticles_api_access_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalarticleorgcontent',
            name='api_access_scheme_label',
            field=models.CharField(blank=True, help_text='Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='api_access_scheme_label',
            field=models.CharField(blank=True, help_text='Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicaltrialorgcontent',
            name='api_access_scheme_label',
            field=models.CharField(blank=True, help_text='Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='api_access_scheme_label',
            field=models.CharField(blank=True, help_text='Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.', max_length=200),
        ),
    ]
