# Generated by Django 6.0.4 on 2026-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0049_historicalarticles_sources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='discovery_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='retracted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='retracted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='recruitment_status',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trials',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='recruitment_status',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='mlpredictions',
            index=models.Index(fields=['article', 'subject', '-created_date'], name='mlpred_art_subj_date_idx'),
        ),
        # Drop pre-existing hand-made single-column indexes now made redundant
        # by the db_index=True AlterFields above (Django creates equivalent,
        # model-managed indexes). Keeps a single index per column. The covering
        # indexes (idx_articles_covering, idx_trials_covering) and
        # idx_trials_discovery_date are NOT duplicated by this migration and are
        # intentionally left in place.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS idx_articles_discovery_date;',
            reverse_sql='CREATE INDEX IF NOT EXISTS idx_articles_discovery_date ON articles (discovery_date);',
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS idx_articles_published_date;',
            reverse_sql='CREATE INDEX IF NOT EXISTS idx_articles_published_date ON articles (published_date);',
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS idx_trials_published_date;',
            reverse_sql='CREATE INDEX IF NOT EXISTS idx_trials_published_date ON trials (published_date);',
        ),
    ]
