# Generated by Django 6.0.4 on 2026-05-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0050_perf_add_indexes_drop_redundant_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='acronym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='results_ipd_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='results_ipd_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='results_yes_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='secondary_sponsor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='acronym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='results_ipd_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='results_ipd_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='results_yes_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='secondary_sponsor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
