# Generated by Django 6.0.4 on 2026-05-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0051_historicaltrials_acronym_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltrials',
            old_name='retrospective_flag',
            new_name='prospective_registration',
        ),
        migrations.RenameField(
            model_name='trials',
            old_name='retrospective_flag',
            new_name='prospective_registration',
        ),
    ]
