# Generated by Django 6.0.4 on 2026-05-31 21:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0052_rename_retrospective_flag_historicaltrials_prospective_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_slug', models.SlugField()),
                ('auto_predict', models.BooleanField(default=False, help_text='Enable automatic ML prediction for new articles')),
                ('ml_consensus_type', models.CharField(choices=[('any', 'Any Model (at least one predicts relevant)'), ('majority', 'Majority Vote (at least 2 out of 3 agree)'), ('all', 'Unanimous (all models must agree)')], default='any', help_text='How ML models should agree for an article to be considered relevant', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.team')),
            ],
            options={
                'verbose_name': 'historical subject',
                'verbose_name_plural': 'historical subjects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
