# Generated by Django 6.0.4 on 2026-06-07 16:25

import django.db.models.fields.json
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0054_trials_swap_title_constraint_for_registry_unique_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('euct', 'identifiers')), condition=models.Q(('identifiers__has_key', 'euct')), name='trials_ueuct_idx'),
        ),
    ]
