# Generated by Django 6.0.4 on 2026-06-07 16:39

import django.db.models.fields.json
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0054_trials_swap_title_constraint_for_registry_unique_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('nct', 'identifiers')), name='trials_unct_idx'),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('eudract', 'identifiers')), name='trials_ueudract_idx'),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('euct', 'identifiers')), name='trials_ueuct_idx'),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('euctr', 'identifiers')), name='trials_ueuctr_idx'),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('ctis', 'identifiers')), name='trials_uctis_idx'),
        ),
    ]
