# Generated by Django 6.0.4 on 2026-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gregory", "0055_trials_registry_identifier_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrials",
            name="links",
            field=models.JSONField(
                blank=True,
                help_text='Registry URLs keyed by registry slug; "link" holds the canonical one',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trials",
            name="links",
            field=models.JSONField(
                blank=True,
                help_text='Registry URLs keyed by registry slug; "link" holds the canonical one',
                null=True,
            ),
        ),
    ]
