# Generated by Django 6.0.4 on 2026-06-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gregory", "0057_teamcategory_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalarticles",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="teamcategory",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When rebuild_categories last synced this category.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamcategory",
            name="match_config_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Fingerprint of the matching configuration (terms, subjects, score threshold) at the last rebuild_categories sync. When the configuration changes, the next incremental run performs a full re-match for this category.",
                max_length=64,
                null=True,
            ),
        ),
    ]
