# Generated by Django 6.0.4 on 2026-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gregory", "0062_articles_last_updated_and_category_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="link",
            field=models.URLField(
                help_text='First URL seen for this article; stable after first import. Corresponds to "link" in the API response.',
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticles",
            name="link",
            field=models.URLField(
                help_text='First URL seen for this article; stable after first import. Corresponds to "link" in the API response.',
                max_length=2000,
            ),
        ),
    ]
