# Generated by Django 6.0.4 on 2026-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0063_alter_articles_link_alter_historicalarticles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='crossref_retraction_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last CrossRef retraction check.', null=True),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='crossref_retraction_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last CrossRef retraction check.', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='retracted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the article has been retracted. Used for filtering and display purposes.'),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='retracted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the article has been retracted. Used for filtering and display purposes.'),
        ),
    ]
