# Generated by Django 6.0.4 on 2026-06-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0065_articles_ml_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticles',
            name='crossref_retraction_check',
        ),
    ]
