# Generated by Django 6.0.6 on 2026-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0068_teamcategory_split_min_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
