# Generated by Django 6.0.6 on 2026-07-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0069_articles_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
