# Generated by Django 6.0.6 on 2026-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0070_authors_biography_historicalauthors_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='relevant',
            field=models.BooleanField(db_index=True, default=False, help_text='Denormalized: manually relevant for any subject, or ML consensus at the 0.8 threshold for any auto_predict subject. Maintained by signals + refresh_article_relevance.'),
        ),
    ]
