# Generated by Django 6.0.6 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0071_articles_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='last_successful_fetch_at',
            field=models.DateTimeField(blank=True, help_text='Start time of the last fetch that completed fully (every page consumed, no errors, result cap not hit). Anchors the incremental ClinicalTrials.gov window; a failed or capped run must not advance it.', null=True),
        ),
    ]
