# Generated by Django 6.0.6 on 2026-07-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0072_sources_last_successful_fetch_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='title',
            field=models.TextField(),
        ),
    ]
