# Generated by Django 6.0.6 on 2026-07-05 23:15
# Hand-adjusted: on long-lived databases the unique on articles.title exists
# as a raw unique INDEX named articles_title_key (not a table constraint), so
# Django's generated ALTER TABLE ... DROP CONSTRAINT fails. Drop whichever
# form exists; the ORM state change is identical either way.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0072_sources_last_successful_fetch_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='articles',
                    name='title',
                    field=models.TextField(),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE articles DROP CONSTRAINT IF EXISTS articles_title_key;',
                        'DROP INDEX IF EXISTS articles_title_key;',
                    ],
                    reverse_sql=[
                        'CREATE UNIQUE INDEX articles_title_key ON articles (title);',
                    ],
                ),
            ],
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='title',
            field=models.TextField(),
        ),
    ]
