# Generated by Django 6.0.6 on 2026-07-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0073_alter_articles_title_alter_historicalarticles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='authors_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='authors_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='details_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='details_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='doi_lookup_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='doi_lookup_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='authors_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='authors_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='details_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='details_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='doi_lookup_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalarticles',
            name='doi_lookup_next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
