# Generated by Django 6.0.6 on 2026-07-11 16:07

import django.db.models.functions.text
from django.db import migrations, models


def check_no_duplicate_dois(apps, schema_editor):
    """Fail early (with a fix hint) if duplicate DOIs would block the constraint.

    AddConstraint would raise on a dirty database anyway; this turns the cryptic
    IntegrityError into an actionable message. Run
    `manage.py merge_duplicate_articles --scan --commit` first.
    """
    from django.db.models import Count
    from django.db.models.functions import Lower

    Articles = apps.get_model("gregory", "Articles")
    dupes = list(
        Articles.objects.exclude(doi__isnull=True)
        .exclude(doi="")
        .annotate(ldoi=Lower("doi"))
        .values("ldoi")
        .annotate(n=Count("article_id"))
        .filter(n__gt=1)
        .values_list("ldoi", flat=True)
    )
    if dupes:
        sample = ", ".join(dupes[:10])
        raise RuntimeError(
            f"{len(dupes)} DOI(s) are held by more than one article "
            f"(e.g. {sample}). Clean them up before applying the "
            "unique_article_doi constraint:\n"
            "  python manage.py merge_duplicate_articles --scan            # preview\n"
            "  python manage.py merge_duplicate_articles --scan --commit   # apply"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0074_articles_authors_attempts_and_more'),
    ]

    operations = [
        migrations.RunPython(
            check_no_duplicate_dois, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='articles',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('doi'), condition=models.Q(('doi__isnull', False), models.Q(('doi', ''), _negated=True)), name='unique_article_doi'),
        ),
    ]
