# Generated by Django 6.0.6 on 2026-07-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('gregory', '0075_article_doi_unique_constraint'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicaltrials',
			name='discovery_date',
			field=models.DateTimeField(blank=True, db_index=True, null=True),
		),
		migrations.AlterField(
			model_name='trials',
			name='discovery_date',
			field=models.DateTimeField(blank=True, db_index=True, null=True),
		),
		# The index already existed as raw SQL (migration 0022) before Django's
		# model state knew about it, so schema-drift checks and fresh test
		# databases relied on that RunSQL instead of a model-managed index.
		# AlterField above adds Django's own index; drop the old hand-made one
		# so prod doesn't end up with two identical indexes on the same column.
		migrations.RunSQL(
			"DROP INDEX IF EXISTS idx_trials_discovery_date;",
			reverse_sql=migrations.RunSQL.noop,
		),
	]
