# Generated by Django 6.0.6 on 2026-07-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('gregory', '0075_article_doi_unique_constraint'),
	]

	operations = [
		# trials.discovery_date already has this exact index, created as raw
		# SQL by migration 0022 (CREATE INDEX idx_trials_discovery_date ...).
		# SeparateDatabaseAndState updates Django's model state to know about
		# it (matching name) without touching the database -- no duplicate
		# index, no rebuild, and reversing this migration only reverts state,
		# leaving the real index from 0022 untouched either way.
		migrations.SeparateDatabaseAndState(
			database_operations=[],
			state_operations=[
				migrations.AddIndex(
					model_name='trials',
					index=models.Index(fields=['discovery_date'], name='idx_trials_discovery_date'),
				),
			],
		),
	]
