# Generated by Django 6.0.6 on 2026-07-12 23:19

from django.db import migrations


def backfill_access_null_to_unknown(apps, schema_editor):
	# NULL and "unknown" are the same semantic state (access was never
	# determined) -- the stats endpoints already fold NULL into "unknown" at
	# read time. Backfill for consistency at rest; write-time code has been
	# updated separately so new rows stop drifting back to NULL.
	Articles = apps.get_model("gregory", "Articles")
	Articles.objects.filter(access__isnull=True).update(access="unknown")


def noop_reverse(apps, schema_editor):
	pass


class Migration(migrations.Migration):

	dependencies = [
		('gregory', '0075_article_doi_unique_constraint'),
	]

	operations = [
		migrations.RunPython(backfill_access_null_to_unknown, noop_reverse),
	]
