# Generated by Django 6.0.6 on 2026-07-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('gregory', '0076_backfill_access_null_to_unknown'),
		('gregory', '0076_trials_discovery_date_model_index'),
	]

	operations = []
