# Generated by Django 6.0.6 on 2026-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0077_merge_access_backfill_and_discovery_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='phase_normalized',
            field=models.CharField(blank=True, choices=[('early_phase_1', 'Early Phase 1'), ('phase_1', 'Phase 1'), ('phase_1_2', 'Phase 1/2'), ('phase_2', 'Phase 2'), ('phase_2_3', 'Phase 2/3'), ('phase_3', 'Phase 3'), ('phase_3_4', 'Phase 3/4'), ('phase_4', 'Phase 4'), ('post_market', 'Post-market'), ('not_applicable', 'Not applicable'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical trial phase derived from the raw 'phase' value; recomputed on every save.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='phase_normalized',
            field=models.CharField(blank=True, choices=[('early_phase_1', 'Early Phase 1'), ('phase_1', 'Phase 1'), ('phase_1_2', 'Phase 1/2'), ('phase_2', 'Phase 2'), ('phase_2_3', 'Phase 2/3'), ('phase_3', 'Phase 3'), ('phase_3_4', 'Phase 3/4'), ('phase_4', 'Phase 4'), ('post_market', 'Post-market'), ('not_applicable', 'Not applicable'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical trial phase derived from the raw 'phase' value; recomputed on every save.", max_length=20, null=True),
        ),
    ]
