# Generated by Django 6.0.6 on 2026-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0078_historicaltrials_phase_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='recruitment_status_normalized',
            field=models.CharField(blank=True, choices=[('not_yet_recruiting', 'Not yet recruiting'), ('recruiting', 'Recruiting'), ('enrolling_by_invitation', 'Enrolling by invitation'), ('active_not_recruiting', 'Active, not recruiting'), ('not_recruiting', 'Not recruiting'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical recruitment status derived from the raw 'recruitment_status' value; recomputed on every save.", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='recruitment_status_normalized',
            field=models.CharField(blank=True, choices=[('not_yet_recruiting', 'Not yet recruiting'), ('recruiting', 'Recruiting'), ('enrolling_by_invitation', 'Enrolling by invitation'), ('active_not_recruiting', 'Active, not recruiting'), ('not_recruiting', 'Not recruiting'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical recruitment status derived from the raw 'recruitment_status' value; recomputed on every save.", max_length=30, null=True),
        ),
    ]
