# Generated by Django 6.0.6 on 2026-07-14 11:41

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0079_historicaltrials_recruitment_status_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='countries_by_source',
            field=models.JSONField(blank=True, help_text='Raw countries value per source registry, e.g. {"ctgov": "France, United States", "ictrp": "France;Iran (Islamic Republic of)"}. Deprecated "countries" column keeps last-writer-wins behaviour.', null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='regions_normalized',
            field=models.JSONField(blank=True, editable=False, help_text="Canonical region slugs (africa, asia, europe, north_america, south_america, oceania) derived from the trial's countries; recomputed on every save.", null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='countries_by_source',
            field=models.JSONField(blank=True, help_text='Raw countries value per source registry, e.g. {"ctgov": "France, United States", "ictrp": "France;Iran (Islamic Republic of)"}. Deprecated "countries" column keeps last-writer-wins behaviour.', null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='regions_normalized',
            field=models.JSONField(blank=True, editable=False, help_text="Canonical region slugs (africa, asia, europe, north_america, south_america, oceania) derived from the trial's countries; recomputed on every save.", null=True),
        ),
        migrations.CreateModel(
            name='TrialCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.CharField(blank=True, choices=[('not_yet_recruiting', 'Not yet recruiting'), ('recruiting', 'Recruiting'), ('enrolling_by_invitation', 'Enrolling by invitation'), ('active_not_recruiting', 'Active, not recruiting'), ('not_recruiting', 'Not recruiting'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=30, null=True)),
                ('status_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_countries', to='gregory.trials')),
            ],
            options={
                'verbose_name': 'trial country',
                'verbose_name_plural': 'trial countries',
                'constraints': [models.UniqueConstraint(fields=('trial', 'country'), name='unique_trial_country')],
            },
        ),
    ]
