# Generated by Django 6.0.6 on 2026-07-16 20:06

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0080_historicaltrials_countries_by_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authors',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('ORCID'), name='gin_trgm_ops'), name='authors_uorcid_gin_idx'),
        ),
    ]
