# Generated by Django 6.0.6 on 2026-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0081_authors_authors_uorcid_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='credit_name',
            field=models.CharField(blank=True, help_text="Researcher's preferred display name from ORCID (person.name.credit-name).", max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='current_affiliation',
            field=models.CharField(blank=True, help_text="Organization name of the author's current (or most recent) employment from ORCID.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='emails',
            field=models.JSONField(blank=True, default=list, help_text='Publicly visible emails from ORCID. Never exposed via the API.'),
        ),
        migrations.AddField(
            model_name='authors',
            name='external_ids',
            field=models.JSONField(blank=True, default=list, help_text="External identifiers from ORCID, e.g. [{'type', 'value', 'url'}]."),
        ),
        migrations.AddField(
            model_name='authors',
            name='orcid_claimed',
            field=models.BooleanField(blank=True, help_text='Whether the ORCID record has been claimed by the researcher.', null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='orcid_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Research keywords from ORCID.'),
        ),
        migrations.AddField(
            model_name='authors',
            name='orcid_verified_email',
            field=models.BooleanField(blank=True, help_text='Whether the ORCID record has a verified email.', null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='researcher_urls',
            field=models.JSONField(blank=True, default=list, help_text="Researcher URLs from ORCID, e.g. [{'name', 'url'}]."),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='credit_name',
            field=models.CharField(blank=True, help_text="Researcher's preferred display name from ORCID (person.name.credit-name).", max_length=301, null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='current_affiliation',
            field=models.CharField(blank=True, help_text="Organization name of the author's current (or most recent) employment from ORCID.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='emails',
            field=models.JSONField(blank=True, default=list, help_text='Publicly visible emails from ORCID. Never exposed via the API.'),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='external_ids',
            field=models.JSONField(blank=True, default=list, help_text="External identifiers from ORCID, e.g. [{'type', 'value', 'url'}]."),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='orcid_claimed',
            field=models.BooleanField(blank=True, help_text='Whether the ORCID record has been claimed by the researcher.', null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='orcid_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Research keywords from ORCID.'),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='orcid_verified_email',
            field=models.BooleanField(blank=True, help_text='Whether the ORCID record has a verified email.', null=True),
        ),
        migrations.AddField(
            model_name='historicalauthors',
            name='researcher_urls',
            field=models.JSONField(blank=True, default=list, help_text="Researcher URLs from ORCID, e.g. [{'name', 'url'}]."),
        ),
    ]
