# Generated by Django 6.0.6 on 2026-07-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0082_authors_orcid_tier1_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='ctis_search_criteria',
            field=models.JSONField(blank=True, help_text='Verbatim searchCriteria dict POSTed to the CTIS public API, e.g. {"medicalCondition": "Multiple Sclerosis"}. Supported keys: medicalCondition, sponsor, number, containAll, status. Only used when method is "CTIS Public API".', null=True, verbose_name='CTIS Public API search criteria'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='method',
            field=models.CharField(choices=[('rss', 'RSS'), ('scrape', 'Scrape'), ('manual', 'Manual submission'), ('ctgov_api', 'ClinicalTrials.gov API'), ('ctis_api', 'CTIS Public API')], default='rss', max_length=10),
        ),
    ]
