# Generated by Django 6.0.6 on 2026-07-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0083_sources_ctis_search_criteria_alter_sources_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sponsor_type', models.CharField(blank=True, choices=[('industry', 'Industry'), ('academic_medical', 'Academic / medical'), ('government', 'Government'), ('nonprofit', 'Non-profit / patient organisation'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('sponsor_type_source', models.CharField(blank=True, max_length=10, null=True)),
                ('oms_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='lead_sponsor_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='lead_sponsor_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='primary_sponsor_normalized',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text="Canonical sponsor entity resolved from the raw 'primary_sponsor' value; recomputed on every save.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.sponsor'),
        ),
        migrations.AddField(
            model_name='trials',
            name='primary_sponsor_normalized',
            field=models.ForeignKey(blank=True, editable=False, help_text="Canonical sponsor entity resolved from the raw 'primary_sponsor' value; recomputed on every save.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='gregory.sponsor'),
        ),
        migrations.CreateModel(
            name='SponsorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, unique=True)),
                ('raw_sample', models.TextField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='gregory.sponsor')),
            ],
        ),
    ]
