# Generated by Django 6.0.6 on 2026-07-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0084_sponsor_historicaltrials_lead_sponsor_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorMergeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(max_length=20)),
                ('shared_key', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('sponsor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gregory.sponsor')),
                ('sponsor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gregory.sponsor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sponsor_a', 'sponsor_b'), name='unique_sponsor_candidate_pair')],
            },
        ),
    ]
