# Generated by Django 6.0.6 on 2026-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0085_sponsormergecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='countries_recruitment_date',
            field=models.JSONField(blank=True, help_text='Per-country recruitment start date from the CTIS retrieve endpoint, keyed by ISO 3166-1 alpha-2 code, e.g. {"IT": "2026-06-26"}. Mirrors countries_decision_date.', null=True),
        ),
        migrations.AddField(
            model_name='trialcountry',
            name='recruitment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='countries_recruitment_date',
            field=models.JSONField(blank=True, help_text='Per-country recruitment start date from the CTIS retrieve endpoint, keyed by ISO 3166-1 alpha-2 code, e.g. {"IT": "2026-06-26"}. Mirrors countries_decision_date.', null=True),
        ),
    ]
