# Generated by Django 6.0.6 on 2026-07-20 00:18

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0086_ctis_retrieve_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('site_type', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('investigator_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_sites', to='gregory.trials')),
            ],
            options={
                'verbose_name': 'trial site',
                'verbose_name_plural': 'trial sites',
            },
        ),
    ]
