# Generated by Django 6.0.6 on 2026-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0087_trial_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcategory',
            name='modality',
            field=models.CharField(blank=True, choices=[('small_molecule', 'Small-molecule drug'), ('biologic_antibody', 'Antibody / biologic'), ('cell_gene_therapy', 'Cell / gene therapy'), ('rehabilitation', 'Rehabilitation / physical'), ('device_neuromodulation', 'Device / neuromodulation'), ('natural_product', 'Natural product / supplement'), ('research_topic', 'Research topic (not an intervention)'), ('other', 'Other')], db_index=True, help_text='Intervention modality group. Curated by hand (seeded by sync_category_modalities); null means not yet classified.', max_length=25, null=True),
        ),
    ]
