# Generated by Django 6.0.6 on 2026-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0088_teamcategory_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='study_type_normalized',
            field=models.CharField(blank=True, choices=[('interventional', 'Interventional'), ('observational', 'Observational'), ('expanded_access', 'Expanded access'), ('basic_science', 'Basic science'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical study type derived from the raw 'study_type' value; recomputed on every save.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='study_type_normalized',
            field=models.CharField(blank=True, choices=[('interventional', 'Interventional'), ('observational', 'Observational'), ('expanded_access', 'Expanded access'), ('basic_science', 'Basic science'), ('other', 'Other')], db_index=True, editable=False, help_text="Canonical study type derived from the raw 'study_type' value; recomputed on every save.", max_length=20, null=True),
        ),
    ]
