# Generated by Django 6.0.6 on 2026-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0089_historicaltrials_study_type_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialsite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialsite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialsite',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trialsite',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
