# Generated by Django 6.0.6 on 2026-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0089_historicaltrials_study_type_normalized_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trialcountry',
            index=models.Index(fields=['country'], name='trialcountry_country_idx'),
        ),
    ]
