# Generated by Django 6.0.6 on 2026-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0090_trial_site_ctgov_capture'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trialsite',
            index=models.Index(fields=['country'], name='trialsite_country_idx'),
        ),
    ]
