# Generated by Django 6.0.6 on 2026-07-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0090_trial_site_ctgov_capture'),
        ('gregory', '0090_trialcountry_country_index'),
    ]

    operations = [
    ]
