# Generated by Django 6.0.6 on 2026-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0091_merge_country_filter_and_ctgov_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='inclusion_gender_normalized',
            field=models.CharField(blank=True, choices=[('all', 'All sexes'), ('female', 'Female only'), ('male', 'Male only')], db_index=True, editable=False, help_text="Canonical sex eligibility (all/female/male) derived from the raw 'inclusion_gender' value; recomputed on every save.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='inclusion_gender_normalized',
            field=models.CharField(blank=True, choices=[('all', 'All sexes'), ('female', 'Female only'), ('male', 'Male only')], db_index=True, editable=False, help_text="Canonical sex eligibility (all/female/male) derived from the raw 'inclusion_gender' value; recomputed on every save.", max_length=10, null=True),
        ),
    ]
