# Generated by Django 6.0.6 on 2026-07-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0092_historicaltrials_inclusion_gender_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='inclusion_age_max_years',
            field=models.FloatField(blank=True, db_index=True, editable=False, help_text="Canonical maximum eligible age in years, derived from 'inclusion_agemax'; recomputed on every save.", null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='inclusion_age_min_years',
            field=models.FloatField(blank=True, db_index=True, editable=False, help_text="Canonical minimum eligible age in years, derived from 'inclusion_agemin'; recomputed on every save.", null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='inclusion_age_max_years',
            field=models.FloatField(blank=True, db_index=True, editable=False, help_text="Canonical maximum eligible age in years, derived from 'inclusion_agemax'; recomputed on every save.", null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='inclusion_age_min_years',
            field=models.FloatField(blank=True, db_index=True, editable=False, help_text="Canonical minimum eligible age in years, derived from 'inclusion_agemin'; recomputed on every save.", null=True),
        ),
    ]
