# Generated by Django 6.0.6 on 2026-08-20 12:08
#
# HOUSE-LOAD-SPIKE-PLAN.md P3: tighten autovacuum on the three highest-churn
# tables so dead-tuple accumulation gets cleaned up sooner under write load.
# Postgres-specific (ALTER TABLE ... SET); ``RunSQL`` with no reverse beyond
# resetting the storage params is safe on any Postgres database, and this
# repo's test suite already requires Postgres (GinIndex, trigram ops
# elsewhere in this app), so no vendor guard is needed.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0093_historicaltrials_inclusion_age_max_years_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE articles SET (autovacuum_vacuum_scale_factor = 0.05, autovacuum_analyze_scale_factor = 0.05);",
            reverse_sql="ALTER TABLE articles RESET (autovacuum_vacuum_scale_factor, autovacuum_analyze_scale_factor);",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE trials SET (autovacuum_vacuum_scale_factor = 0.05, autovacuum_analyze_scale_factor = 0.05);",
            reverse_sql="ALTER TABLE trials RESET (autovacuum_vacuum_scale_factor, autovacuum_analyze_scale_factor);",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE articles_authors SET (autovacuum_vacuum_scale_factor = 0.05, autovacuum_analyze_scale_factor = 0.05);",
            reverse_sql="ALTER TABLE articles_authors RESET (autovacuum_vacuum_scale_factor, autovacuum_analyze_scale_factor);",
        ),
    ]
