# Generated by Django 6.0.6 on 2026-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0094_autovacuum_tuning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
