# Generated by Django 6.0.6 on 2026-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0094_autovacuum_tuning'),
    ]

    operations = [
        # Databases that applied 0073 before it learned to drop this index still
        # carry it orphaned, and the AlterField below would collide recreating it.
        # No-op on dev/House, which never had it. See 0073 for the full story.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS articles_title_ed7ced3d_like;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalarticles',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrials',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trials',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
