# Generated by Django 6.0.6 on 2026-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0095_index_title_and_discovery_date_ordering_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_listed',
            field=models.BooleanField(default=False, help_text="Whether this team is listed in /teams/. Gates listing only -- it does not affect access to this team's content, which is governed entirely by whether its subjects are in a public site's scope (CustomSetting.scope_subjects + api_public). Conflating the two would let a metadata switch quietly become a data-visibility switch. Seeded True at migration time for every team that owned a subject in a public site's scope; free to override in either direction afterwards -- e.g. to hide an internal lab's name from a public listing, or to credit a partner team that owns no in-scope subjects."),
        ),
    ]
