# Generated by Django 6.0.6 on 2026-09-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0096_team_api_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='site',
        ),
    ]
