# Generated by Django 6.0.6 on 2026-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0097_remove_team_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationapisettings',
            name='make_api_public',
            field=models.BooleanField(default=False, help_text='When true, anonymous callers can see this organisation in /organizations/, validate ?team_id=/?organization= against it, and see its per-org serializer fields via ?team_id=. Does NOT govern article/trial/RSS content visibility -- that is CustomSetting.scope_subjects + api_public on the site(s) this organisation owns.'),
        ),
    ]
