# Generated by Django 6.0.6 on 2026-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0098_alter_organizationapisettings_make_api_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsite',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Mark this as the default site for the organization. Used as the fallback when a List has no explicit site (subscriptions.Lists.save()), and to resolve an organisation's API keys to one site."),
        ),
    ]
