# Generated by Django 6.0.6 on 2026-09-18 14:20

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0099_alter_organizationsite_is_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trials',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('scientific_title'), name='gin_trgm_ops'), name='trials_uscititle_gin_idx'),
        ),
    ]
