# Generated by Django 6.0.6 on 2026-09-18 15:20

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0100_trials_trials_uscientific_title_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='ctg_secondary_ids',
            field=models.JSONField(blank=True, help_text='Verbatim secondaryIdInfos from ClinicalTrials.gov (id, type, domain, link). [] = none listed; null = not fetched yet.', null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='identifiers_normalized',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, editable=False, help_text='Canonical registry IDs as "type:VALUE", e.g. ["eudract:2021-003034-37", "isrctn:ISRCTN14048364"]. Derived from identifiers, secondary_id and ctg_secondary_ids; recomputed on every save.', null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='ctg_secondary_ids',
            field=models.JSONField(blank=True, help_text='Verbatim secondaryIdInfos from ClinicalTrials.gov (id, type, domain, link). [] = none listed; null = not fetched yet.', null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='identifiers_normalized',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, editable=False, help_text='Canonical registry IDs as "type:VALUE", e.g. ["eudract:2021-003034-37", "isrctn:ISRCTN14048364"]. Derived from identifiers, secondary_id and ctg_secondary_ids; recomputed on every save.', null=True),
        ),
        migrations.AddIndex(
            model_name='trials',
            index=django.contrib.postgres.indexes.GinIndex(fields=['identifiers_normalized'], name='trials_ids_norm_gin_idx'),
        ),
    ]
