# Generated by Django 6.0.6 on 2026-10-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0101_historicaltrials_ctg_secondary_ids_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsite',
            name='site',
            field=models.ForeignKey(help_text='The Django site associated with this organization. A site belongs to exactly one organization.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_sites', to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='organizationsite',
            constraint=models.UniqueConstraint(fields=('site',), name='unique_site_organization'),
        ),
    ]
