# Generated by Django 6.0.6 on 2026-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0102_unique_site_per_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationapisettings',
            name='make_api_public',
            field=models.BooleanField(default=False, help_text='When true, anonymous callers can see this organisation in /organizations/ and validate ?team_id=/?organization= against it. Does NOT govern article/trial/RSS content visibility -- that is CustomSetting.scope_subjects + api_public on the site(s) this organisation owns.'),
        ),
    ]
