# Generated by Django 6.0.6 on 2026-10-03 16:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("api", "0007_apiaccessscheme_site"),
		("gregory", "0103_organizationapisettings_make_api_public_help"),
		("sites", "0002_alter_domain_unique"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="HistoricalArticleSiteContent",
			fields=[
				(
					"id",
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name="ID"
					),
				),
				(
					"api_access_scheme_label",
					models.CharField(
						blank=True,
						help_text="Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.",
						max_length=200,
					),
				),
				("takeaways", models.TextField(blank=True, null=True)),
				("summary_plain_english", models.TextField(blank=True, null=True)),
				("created_at", models.DateTimeField(blank=True, editable=False)),
				("updated_at", models.DateTimeField(blank=True, editable=False)),
				("history_id", models.AutoField(primary_key=True, serialize=False)),
				("history_date", models.DateTimeField(db_index=True)),
				("history_change_reason", models.CharField(max_length=100, null=True)),
				(
					"history_type",
					models.CharField(
						choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
						max_length=1,
					),
				),
				(
					"api_access_scheme",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="api.apiaccessscheme",
					),
				),
				(
					"article",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="gregory.articles",
					),
				),
				(
					"history_user",
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"site",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="sites.site",
					),
				),
			],
			options={
				"verbose_name": "historical article site content",
				"verbose_name_plural": "historical article site contents",
				"ordering": ("-history_date", "-history_id"),
				"get_latest_by": ("history_date", "history_id"),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name="ArticleSiteContent",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("takeaways", models.TextField(blank=True, null=True)),
				("summary_plain_english", models.TextField(blank=True, null=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"article",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="site_contents",
						to="gregory.articles",
					),
				),
				(
					"site",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="article_contents",
						to="sites.site",
					),
				),
			],
			options={
				"verbose_name": "article site content",
				"verbose_name_plural": "article site contents",
				"constraints": [
					models.UniqueConstraint(
						fields=("article", "site"), name="unique_article_site_content"
					)
				],
			},
		),
	]
