# Generated by Django 6.0.6 on 2026-10-03 16:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("api", "0007_apiaccessscheme_site"),
		("gregory", "0105_copy_org_content_to_site_content"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name="articletrialreference",
			name="created_by",
			field=models.ForeignKey(
				blank=True,
				help_text="The editor who added a manual link. NULL for auto rows.",
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="+",
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.AddField(
			model_name="articletrialreference",
			name="source",
			field=models.CharField(
				choices=[("auto", "Auto-detected"), ("manual", "Added by an editor")],
				default="auto",
				help_text="auto: found by detect_trial_references. manual: added by an editor, with identifier_type 'manual'. Detection never touches manual rows.",
				max_length=10,
			),
		),
		migrations.AddField(
			model_name="articletrialreference",
			name="suppressed",
			field=models.BooleanField(
				default=False,
				help_text="Set when an editor unlinks an auto-detected link. The row is hidden from every read and detect_trial_references leaves it alone, so the next detection run doesn't recreate the link.",
			),
		),
		migrations.AddField(
			model_name="historicalarticlesitecontent",
			name="editor_label",
			field=models.CharField(
				blank=True,
				help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.",
				max_length=300,
			),
		),
		migrations.AddField(
			model_name="historicalarticlesitecontent",
			name="editor_user",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="+",
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.AddField(
			model_name="historicalarticlesitecontent",
			name="via",
			field=models.CharField(
				blank=True,
				choices=[("mcp", "MCP"), ("api_key", "API key"), ("admin", "Admin")],
				help_text="Which door the change came through.",
				max_length=20,
			),
		),
		migrations.CreateModel(
			name="HistoricalArticleSubjectRelevance",
			fields=[
				(
					"id",
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name="ID"
					),
				),
				(
					"api_access_scheme_label",
					models.CharField(
						blank=True,
						help_text="Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.",
						max_length=200,
					),
				),
				(
					"editor_label",
					models.CharField(
						blank=True,
						help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.",
						max_length=300,
					),
				),
				(
					"via",
					models.CharField(
						blank=True,
						choices=[
							("mcp", "MCP"),
							("api_key", "API key"),
							("admin", "Admin"),
						],
						help_text="Which door the change came through.",
						max_length=20,
					),
				),
				(
					"is_relevant",
					models.BooleanField(
						blank=True,
						default=None,
						help_text="Indicates if the article is relevant for the subject. NULL means not reviewed.",
						null=True,
					),
				),
				("history_id", models.AutoField(primary_key=True, serialize=False)),
				("history_date", models.DateTimeField(db_index=True)),
				("history_change_reason", models.CharField(max_length=100, null=True)),
				(
					"history_type",
					models.CharField(
						choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
						max_length=1,
					),
				),
				(
					"api_access_scheme",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="api.apiaccessscheme",
					),
				),
				(
					"article",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="gregory.articles",
					),
				),
				(
					"editor_user",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"history_user",
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"subject",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="gregory.subject",
					),
				),
			],
			options={
				"verbose_name": "historical article subject relevance",
				"verbose_name_plural": "historical article subject relevances",
				"ordering": ("-history_date", "-history_id"),
				"get_latest_by": ("history_date", "history_id"),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name="HistoricalArticleTrialReference",
			fields=[
				(
					"id",
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name="ID"
					),
				),
				(
					"api_access_scheme_label",
					models.CharField(
						blank=True,
						help_text="Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.",
						max_length=200,
					),
				),
				(
					"editor_label",
					models.CharField(
						blank=True,
						help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.",
						max_length=300,
					),
				),
				(
					"via",
					models.CharField(
						blank=True,
						choices=[
							("mcp", "MCP"),
							("api_key", "API key"),
							("admin", "Admin"),
						],
						help_text="Which door the change came through.",
						max_length=20,
					),
				),
				(
					"identifier_type",
					models.CharField(
						help_text="Which identifier was found (e.g., 'nct_id', 'isrctn')",
						max_length=50,
					),
				),
				(
					"identifier_value",
					models.CharField(
						help_text="The actual identifier value", max_length=100
					),
				),
				("discovered_date", models.DateTimeField(blank=True, editable=False)),
				(
					"source",
					models.CharField(
						choices=[
							("auto", "Auto-detected"),
							("manual", "Added by an editor"),
						],
						default="auto",
						help_text="auto: found by detect_trial_references. manual: added by an editor, with identifier_type 'manual'. Detection never touches manual rows.",
						max_length=10,
					),
				),
				(
					"suppressed",
					models.BooleanField(
						default=False,
						help_text="Set when an editor unlinks an auto-detected link. The row is hidden from every read and detect_trial_references leaves it alone, so the next detection run doesn't recreate the link.",
					),
				),
				("history_id", models.AutoField(primary_key=True, serialize=False)),
				("history_date", models.DateTimeField(db_index=True)),
				("history_change_reason", models.CharField(max_length=100, null=True)),
				(
					"history_type",
					models.CharField(
						choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
						max_length=1,
					),
				),
				(
					"api_access_scheme",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="api.apiaccessscheme",
					),
				),
				(
					"article",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="gregory.articles",
					),
				),
				(
					"created_by",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						help_text="The editor who added a manual link. NULL for auto rows.",
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"editor_user",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"history_user",
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"trial",
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="+",
						to="gregory.trials",
					),
				),
			],
			options={
				"verbose_name": "historical article trial reference",
				"verbose_name_plural": "historical article trial references",
				"ordering": ("-history_date", "-history_id"),
				"get_latest_by": ("history_date", "history_id"),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
	]
