# Generated by Django 6.0.6 on 2026-10-09 21:49

import django.contrib.postgres.fields
import django.db.models.deletion
import gregory.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_apiaccessscheme_site"),
        ("gregory", "0106_editor_history_and_trial_link_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalArticleCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "api_access_scheme_label",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.",
                        max_length=200,
                    ),
                ),
                (
                    "editor_label",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.",
                        max_length=300,
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mcp", "MCP"),
                            ("api_key", "API key"),
                            ("admin", "Admin"),
                        ],
                        help_text="Which door the change came through.",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "api_access_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.apiaccessscheme",
                    ),
                ),
                (
                    "articles",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gregory.articles",
                    ),
                ),
                (
                    "editor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teamcategory",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gregory.teamcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical article category assignment",
                "verbose_name_plural": "historical article category assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTeamCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "api_access_scheme_label",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.",
                        max_length=200,
                    ),
                ),
                (
                    "editor_label",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.",
                        max_length=300,
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mcp", "MCP"),
                            ("api_key", "API key"),
                            ("admin", "Admin"),
                        ],
                        help_text="Which door the change came through.",
                        max_length=20,
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("category_description", models.TextField(blank=True, null=True)),
                ("category_slug", models.SlugField(blank=True, null=True)),
                (
                    "category_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Add terms separated by commas.",
                        verbose_name="Terms to include in category (comma separated)",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="automatic",
                        help_text="Automatic categories are populated by the rebuild_categories command from the term list (manual assignments are still allowed and preserved). Manual categories are curated entirely by hand and are never touched by the command.",
                        max_length=10,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small_molecule", "Small-molecule drug"),
                            ("biologic_antibody", "Antibody / biologic"),
                            ("cell_gene_therapy", "Cell / gene therapy"),
                            ("rehabilitation", "Rehabilitation / physical"),
                            ("device_neuromodulation", "Device / neuromodulation"),
                            ("natural_product", "Natural product / supplement"),
                            ("research_topic", "Research topic (not an intervention)"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Intervention modality group. Curated by hand (seeded by sync_category_modalities); null means not yet classified.",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "match_scope",
                    models.CharField(
                        choices=[
                            ("title", "Title only"),
                            ("title_summary", "Title and summary"),
                        ],
                        default="title_summary",
                        help_text="Which fields are searched and scored when matching content to this category. 'Title only' scores just the title; 'Title and summary' also scores the summary (and, for trials, the scientific title, intervention, outcomes and therapeutic areas).",
                        max_length=20,
                    ),
                ),
                (
                    "match_min_score_articles",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Minimum score an article must reach to be assigned to this category. Articles are scored on up to 2 fields (title, summary).",
                    ),
                ),
                (
                    "match_min_score_trials",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Minimum score a trial must reach to be assigned to this category. Trials are scored on up to 7 fields (title, summary, scientific title, intervention, primary outcome, secondary outcome, therapeutic areas).",
                    ),
                ),
                (
                    "match_weights",
                    models.JSONField(
                        blank=True,
                        default=gregory.models.default_match_weights,
                        help_text="Per-field score weights keyed by content type ('article', 'trial'). Higher weights make a matched field count for more. A fixed bonus of 2 points per unique matched term is always added.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "api_access_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.apiaccessscheme",
                    ),
                ),
                (
                    "editor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gregory.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team category",
                "verbose_name_plural": "historical team categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
