# Generated by Django 6.0.6 on 2026-10-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0107_teamcategory_and_assignment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrials',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='completion_date_type',
            field=models.CharField(blank=True, choices=[('actual', 'Actual'), ('estimated', 'Estimated')], help_text='Whether the completion dates are actual or estimated, as reported by the registry.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrials',
            name='primary_completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='completion_date_type',
            field=models.CharField(blank=True, choices=[('actual', 'Actual'), ('estimated', 'Estimated')], help_text='Whether the completion dates are actual or estimated, as reported by the registry.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trials',
            name='primary_completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
