# Generated by Django 6.0.6 on 2026-10-10 21:17

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import gregory.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apiaccessscheme_site'),
        ('gregory', '0108_trial_completion_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteamcategory',
            name='match_min_score_patents',
            field=models.PositiveSmallIntegerField(default=3, help_text='Minimum score a patent must reach to be assigned to this category. Patents are scored on up to 3 fields (title, summary, claims).'),
        ),
        migrations.AddField(
            model_name='organizationcredentials',
            name='epo_ops_consumer_key',
            field=gregory.models.EncryptedTextField(blank=True, help_text='EPO Open Patent Services consumer key for this organization.', null=True),
        ),
        migrations.AddField(
            model_name='organizationcredentials',
            name='epo_ops_consumer_secret',
            field=gregory.models.EncryptedTextField(blank=True, help_text='EPO Open Patent Services consumer secret for this organization.', null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='ops_cql_query',
            field=models.TextField(blank=True, help_text='CQL query for EPO Open Patent Services, e.g. ta="multiple sclerosis" and cpc=/low A61P25/00. Leave out any publication date (pd) clause: the importer adds the date window itself. Only used when method is "EPO Open Patent Services".', null=True, verbose_name='EPO OPS CQL query'),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='match_min_score_patents',
            field=models.PositiveSmallIntegerField(default=3, help_text='Minimum score a patent must reach to be assigned to this category. Patents are scored on up to 3 fields (title, summary, claims).'),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='patent_match_config_hash',
            field=models.CharField(blank=True, editable=False, help_text='Same as match_config_hash, for the patent pass. Kept separate so that adding patent matching never forces a full article and trial re-match.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='method',
            field=models.CharField(choices=[('rss', 'RSS'), ('scrape', 'Scrape'), ('manual', 'Manual submission'), ('ctgov_api', 'ClinicalTrials.gov API'), ('ctis_api', 'CTIS Public API'), ('epo_ops', 'EPO Open Patent Services')], default='rss', max_length=10),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_for',
            field=models.CharField(choices=[('science paper', 'Science Paper'), ('trials', 'Trials'), ('news article', 'News Article'), ('patents', 'Patents')], default='science paper', max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricalPatents',
            fields=[
                ('api_access_scheme_label', models.CharField(blank=True, help_text='Snapshot of APIAccessScheme.client_name at the time of the change. Preserved after key deletion.', max_length=200)),
                ('editor_label', models.CharField(blank=True, help_text="Snapshot of the editor's name and email at the time of the change. Preserved after the user is deleted.", max_length=300)),
                ('via', models.CharField(blank=True, choices=[('mcp', 'MCP'), ('api_key', 'API key'), ('admin', 'Admin')], help_text='Which door the change came through.', max_length=20)),
                ('patent_id', models.IntegerField(blank=True, db_index=True)),
                ('family_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('title', models.TextField(db_index=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('claims', models.TextField(blank=True, null=True)),
                ('representative_publication', models.CharField(blank=True, default='', max_length=32)),
                ('link', models.URLField(blank=True, default='', max_length=2000)),
                ('links', models.JSONField(blank=True, help_text='URLs keyed by source slug (e.g. "espacenet"); "link" holds the canonical one', null=True)),
                ('earliest_priority_date', models.DateField(blank=True, db_index=True, null=True)),
                ('earliest_publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('has_grant', models.BooleanField(default=False, help_text='True when any member publication has a grant kind code. Heuristic until legal status is fetched.')),
                ('cpc_classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('ipc_classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('inventors', models.JSONField(blank=True, default=list)),
                ('discovery_date', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('family_next_check', models.DateTimeField(blank=True, null=True)),
                ('family_attempts', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('api_access_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.apiaccessscheme')),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patent family',
                'verbose_name_plural': 'historical patents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PatentApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=500)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_individual', models.BooleanField(default=False)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patent_applications', to='gregory.sponsor')),
            ],
            options={
                'db_table': 'patent_applicants',
                'ordering': ['patent_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PatentCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10)),
                ('teamcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_assignments', to='gregory.teamcategory')),
            ],
            options={
                'verbose_name': 'patent category assignment',
                'db_table': 'patents_team_categories',
            },
        ),
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('patent_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('claims', models.TextField(blank=True, null=True)),
                ('utitle', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('title'), output_field=models.TextField())),
                ('usummary', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('summary'), output_field=models.TextField())),
                ('representative_publication', models.CharField(blank=True, default='', max_length=32)),
                ('link', models.URLField(blank=True, default='', max_length=2000)),
                ('links', models.JSONField(blank=True, help_text='URLs keyed by source slug (e.g. "espacenet"); "link" holds the canonical one', null=True)),
                ('earliest_priority_date', models.DateField(blank=True, db_index=True, null=True)),
                ('earliest_publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('has_grant', models.BooleanField(default=False, help_text='True when any member publication has a grant kind code. Heuristic until legal status is fetched.')),
                ('cpc_classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('ipc_classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('inventors', models.JSONField(blank=True, default=list)),
                ('discovery_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('family_next_check', models.DateTimeField(blank=True, null=True)),
                ('family_attempts', models.PositiveSmallIntegerField(default=0)),
                ('applicants', models.ManyToManyField(blank=True, related_name='patents', through='gregory.PatentApplicant', to='gregory.sponsor')),
                ('sources', models.ManyToManyField(blank=True, to='gregory.sources')),
                ('subjects', models.ManyToManyField(blank=True, related_name='patents', to='gregory.subject')),
                ('team_categories', models.ManyToManyField(related_name='patents', through='gregory.PatentCategoryAssignment', to='gregory.teamcategory')),
                ('teams', models.ManyToManyField(blank=True, related_name='patents', to='gregory.team')),
            ],
            options={
                'verbose_name': 'patent family',
                'verbose_name_plural': 'patents',
                'db_table': 'patents',
                'ordering': ['-discovery_date'],
            },
        ),
        migrations.CreateModel(
            name='PatentPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_number', models.CharField(max_length=32, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=4)),
                ('doc_number', models.CharField(blank=True, default='', max_length=32)),
                ('kind', models.CharField(blank=True, default='', max_length=4)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=40, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('lens_id', models.CharField(blank=True, max_length=40, null=True)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='gregory.patents')),
            ],
            options={
                'db_table': 'patent_publications',
                'ordering': ['publication_date', 'publication_number'],
            },
        ),
        migrations.AddField(
            model_name='patentcategoryassignment',
            name='patents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='gregory.patents'),
        ),
        migrations.AddField(
            model_name='patentapplicant',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_applicants', to='gregory.patents'),
        ),
        migrations.CreateModel(
            name='HistoricalPatents_teams',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='gregory.historicalpatents')),
                ('team', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.team')),
                ('patents', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.patents')),
            ],
            options={
                'verbose_name': 'HistoricalPatents_teams',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatents_subjects',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='gregory.historicalpatents')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.subject')),
                ('patents', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.patents')),
            ],
            options={
                'verbose_name': 'HistoricalPatents_subjects',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatents_sources',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='gregory.historicalpatents')),
                ('sources', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.sources')),
                ('patents', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gregory.patents')),
            ],
            options={
                'verbose_name': 'HistoricalPatents_sources',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='patents',
            index=django.contrib.postgres.indexes.GinIndex(fields=['utitle'], name='patents_utitle_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patents',
            index=django.contrib.postgres.indexes.GinIndex(fields=['usummary'], name='patents_usummary_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patents',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cpc_classes'], name='patents_cpc_gin_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patentcategoryassignment',
            unique_together={('patents', 'teamcategory')},
        ),
        migrations.AddConstraint(
            model_name='patentapplicant',
            constraint=models.UniqueConstraint(fields=('patent', 'sequence'), name='uniq_patent_applicant_seq'),
        ),
    ]
