# Generated by Django 6.0.6 on 2026-10-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0109_patents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentTrialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('during', 'Filed during the trial'), ('after', 'Filed after the trial ended')], max_length=10)),
                ('days_after_completion', models.IntegerField(blank=True, help_text="For 'after' links: days between the trial's completion and the patent's earliest priority date.", null=True)),
                ('basis', models.CharField(choices=[('category', 'Shared team category'), ('subject', 'Shared subject only')], help_text="'category' when the patent and the trial share a team category (typically the molecule), the strong signal. 'subject' when they share only a subject; noisy for large sponsors.", max_length=10)),
                ('suppressed', models.BooleanField(default=False, help_text='Set when an editor dismissed the link. Detection never recreates or changes a suppressed link.')),
                ('discovered_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_links', to='gregory.patents')),
                ('sponsor', models.ForeignKey(help_text='The sponsor shared by the patent (as applicant) and the trial.', on_delete=django.db.models.deletion.CASCADE, related_name='patent_trial_links', to='gregory.sponsor')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_links', to='gregory.trials')),
            ],
            options={
                'verbose_name': 'patent-trial link',
                'db_table': 'patent_trial_links',
                'constraints': [models.UniqueConstraint(fields=('patent', 'trial'), name='unique_patent_trial_link')],
            },
        ),
    ]
