# syntax=docker/dockerfile:1
FROM python:3.12-slim AS base

# Install only necessary system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# Environment variables to optimize Python behavior
ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1 \
	PYTHONPATH="/code"

# Set working directory
WORKDIR /code

# Upgrade pip and install dependencies
COPY requirements.txt /code/
# Install system dependencies required to build Python packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gcc \
        python3-dev \
        libatlas-base-dev \
        libffi-dev \
        libxml2-dev \
        libxslt1-dev \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip \
	&& pip install --no-cache-dir -r requirements.txt

# Copy application code (optional if used in multi-stage builds)
COPY . /code