[pytest]
DJANGO_SETTINGS_MODULE = admin.settings_test
python_files = test_*.py tests.py
python_classes = Test*
python_functions = test_*
testpaths = api gregory subscriptions indexers rss sitesettings
addopts = --reuse-db --no-migrations --dist loadfile -n auto
