# Generated by Django 4.0.4 on 2022-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=150)),
                ('list_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'lists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('clinical centre', 'Clinical Centre'), ('researcher', 'Researcher')], default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('subscriptions', models.ManyToManyField(blank=True, to='subscriptions.lists')),
            ],
            options={
                'verbose_name_plural': 'subscribers',
                'db_table': 'subscribers',
                'managed': True,
            },
        ),
    ]
