# Generated by Django 5.2.3 on 2025-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0013_alter_articles_unique_together_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='latest_research_categories',
            field=models.ManyToManyField(blank=True, help_text="Select team categories to include in the 'Latest Research' section of weekly digest emails.", related_name='latest_research_lists', to='gregory.teamcategory', verbose_name='Latest Research Categories'),
        ),
    ]
