# Generated by Django 5.2.3 on 2025-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_latest_research_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='article_limit',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Maximum number of articles to include in weekly digest emails (default: 15)', null=True),
        ),
    ]
