# Generated by Django 5.2.3 on 2025-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_lists_article_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='article_limit',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Maximum number of articles to include in weekly digest emails (default: 15)', null=True, verbose_name='Article Limit for Weekly Digest Emails'),
        ),
    ]
