# Generated by Django 5.2.3 on 2025-08-06 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_lists_article_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='ml_threshold',
            field=models.FloatField(default=0.8, help_text='ML prediction confidence threshold (0.0-1.0). Only articles with ML predictions above this threshold will be considered relevant.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='ML Threshold for Relevance'),
        ),
    ]
