# Generated by Django 6.0.3 on 2026-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_add_ml_threshold_to_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscribers',
            name='profile',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('doctor', 'Doctor'), ('clinical centre', 'Clinical Centre'), ('researcher', 'Researcher')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='profile',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('doctor', 'Doctor'), ('clinical centre', 'Clinical Centre'), ('researcher', 'Researcher')], default='', max_length=50),
        ),
    ]
