# Generated by Django 6.0.3 on 2026-04-16 20:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0007_lists_allowed_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscribers',
            name='unsubscribe_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique token used in unsubscribe links. Never expose this outside of email context.'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='unsubscribe_token',
            # Add as nullable first; data migration (0009) backfills unique UUIDs;
            # migration 0010 then adds the unique constraint.
            field=models.UUIDField(null=True, editable=False, help_text='Unique token used in unsubscribe links. Never expose this outside of email context.'),
        ),
        migrations.CreateModel(
            name='HistoricalListSubscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(blank=True, editable=False)),
                ('consent_ip', models.GenericIPAddressField(blank=True, help_text='IP address at the time of subscription (for GDPR audit trail).', null=True)),
                ('consent_method', models.CharField(choices=[('web_form', 'Web Form'), ('admin', 'Admin'), ('api', 'API'), ('import', 'Import')], default='web_form', help_text='How this subscription was obtained.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to unsubscribe this subscriber from this specific list.')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Timestamp when the subscriber opted out of this list.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent_source_site', models.ForeignKey(blank=True, db_constraint=False, help_text='The site the subscription form was submitted from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.lists')),
                ('subscriber', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscribers')),
            ],
            options={
                'verbose_name': 'historical List Subscription',
                'verbose_name_plural': 'historical List Subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ListSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, help_text='IP address at the time of subscription (for GDPR audit trail).', null=True)),
                ('consent_method', models.CharField(choices=[('web_form', 'Web Form'), ('admin', 'Admin'), ('api', 'API'), ('import', 'Import')], default='web_form', help_text='How this subscription was obtained.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to unsubscribe this subscriber from this specific list.')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Timestamp when the subscriber opted out of this list.', null=True)),
                ('consent_source_site', models.ForeignKey(blank=True, help_text='The site the subscription form was submitted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subscriptions', to='sites.site')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_subscriptions', to='subscriptions.lists')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_subscriptions', to='subscriptions.subscribers')),
            ],
            options={
                'verbose_name': 'List Subscription',
                'verbose_name_plural': 'List Subscriptions',
                'unique_together': {('subscriber', 'list')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberSiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('doctor', 'Doctor'), ('clinical centre', 'Clinical Centre'), ('researcher', 'Researcher')], default='', help_text="The subscriber's role on this specific site.", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profiles', to='sites.site')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_profiles', to='subscriptions.subscribers')),
            ],
            options={
                'verbose_name': 'Subscriber Site Profile',
                'verbose_name_plural': 'Subscriber Site Profiles',
                'unique_together': {('subscriber', 'site')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalSubscribers_subscriptions',
        ),
    ]
