# Generated by Django 6.0.3 on 2026-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_announcement_announcementrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='header_tagline',
            field=models.CharField(blank=True, default='', help_text='Optional subtitle/tagline shown below the site name in the email header. Leave blank for default.', max_length=200, verbose_name='Header Tagline'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='header_title',
            field=models.CharField(blank=True, default='', help_text='Optional title shown in the email header box. Leave blank to hide the title box.', max_length=200, verbose_name='Header Title'),
        ),
    ]
