# Generated by Django 6.0.4 on 2026-04-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0015_announcement_header_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='site',
            field=models.ForeignKey(default=1, help_text='The site this list sends emails from. Determines footer branding, links, and unsubscribe URLs.', on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='header_title',
            field=models.CharField(blank=True, default='', help_text='Replaces the Gregory AI title in the email header. Leave blank to use the default site title.', max_length=200, verbose_name='Header Title'),
        ),
    ]
