# Generated by Django 6.0.4 on 2026-04-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0016_lists_site_alter_announcement_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this list sends emails from. Determines footer branding, links, and unsubscribe URLs. Auto-populated from the organisation default site if not set.', on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='sites.site'),
        ),
    ]
