# Generated by Django 6.0.4 on 2026-04-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_alter_lists_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscribers',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='profile',
        ),
    ]
