# Generated by Django 6.0.4 on 2026-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_remove_historicalsubscribers_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='preheader_text',
            field=models.CharField(blank=True, default='', help_text='Short preview text shown in email clients before the email is opened. Leave blank for a default message.', max_length=200, verbose_name='Preheader Text'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_header_tagline',
            field=models.BooleanField(default=True, help_text='Uncheck to hide the tagline from the email header entirely.', verbose_name='Show Header Tagline'),
        ),
    ]
