# Generated by Django 6.0.4 on 2026-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_add_other_profile_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribersiteprofile',
            name='profile',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clinical centre', 'Clinical Centre'), ('researcher', 'Researcher'), ('other', 'Other')], default='', help_text="The subscriber's role on this specific site.", max_length=50),
        ),
    ]
