# Generated by Django 6.0.4 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_add_nurse_profile_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='header_tagline',
            field=models.CharField(blank=True, help_text='Optional tagline to display in the email header.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lists',
            name='header_title',
            field=models.CharField(blank=True, help_text='Optional override for the email header title (defaults to "Gregory AI").', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lists',
            name='show_header_tagline',
            field=models.BooleanField(default=True, help_text='Show the tagline in the email header.'),
        ),
    ]
