# Generated by Django 6.0.4 on 2026-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_lists_header_tagline_lists_header_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='article_sort_order',
            field=models.CharField(choices=[('relevancy', 'Relevancy (manual + ML consensus, ranked)'), ('date', 'Date (all subject-matched articles, newest first)')], default='relevancy', help_text="How articles are selected and ordered in weekly digest emails. 'relevancy' applies ML/manual filtering and priority ranking. 'date' includes all subject-matched articles ordered by discovery date (newest first).", max_length=20, verbose_name='Article Sort Order'),
        ),
    ]
