# Generated by Django 6.0.4 on 2026-05-09 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_lists_article_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='lookback_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days back to look for articles and trials in the weekly digest. Common values: 8, 15, 30. Maximum 365.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Lookback Window (days)'),
        ),
    ]
