# Generated by Django 6.0.4 on 2026-05-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('subscriptions', '0025_lists_lookback_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns this announcement. Determines who can see and edit it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organizations.organization'),
        ),
    ]
