# Generated by Django 6.0.4 on 2026-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_announcement_organization_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscribers',
            name='active',
            field=models.BooleanField(default=True, help_text="Global email switch for this subscriber. When unchecked, they receive NO emails from any list — a master opt-out that is independent of the individual list subscriptions below. It is set automatically when someone unsubscribes from everything, and manually via the 'Disable all emails' admin action. Per-list opt-outs do NOT change this flag. Note: the 'Total Active Subscribers' analytics chart and snapshot KPIs count someone as 'active' by whether they hold at least one active list subscription, not by this flag, so those numbers can differ from the active/inactive account counts. (Other analytics surfaces, such as the profile and recent-subscriber views, do still filter on this flag.)"),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='active',
            field=models.BooleanField(default=True, help_text="Global email switch for this subscriber. When unchecked, they receive NO emails from any list — a master opt-out that is independent of the individual list subscriptions below. It is set automatically when someone unsubscribes from everything, and manually via the 'Disable all emails' admin action. Per-list opt-outs do NOT change this flag. Note: the 'Total Active Subscribers' analytics chart and snapshot KPIs count someone as 'active' by whether they hold at least one active list subscription, not by this flag, so those numbers can differ from the active/inactive account counts. (Other analytics surfaces, such as the profile and recent-subscriber views, do still filter on this flag.)"),
        ),
    ]
