# Generated by Django 6.0.4 on 2026-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_announcement_organization_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscribers',
            name='active',
            field=models.BooleanField(default=True, help_text="Global email switch for this subscriber. When unchecked, they receive NO emails from any list — a master opt-out that is independent of the individual list subscriptions below. It is set automatically when someone unsubscribes from everything, and manually via the 'Disable all emails' admin action. Per-list opt-outs do NOT change this flag. Note: subscriber analytics counts someone as 'active' when they hold at least one active list subscription, not by this flag, so the two numbers can differ."),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='active',
            field=models.BooleanField(default=True, help_text="Global email switch for this subscriber. When unchecked, they receive NO emails from any list — a master opt-out that is independent of the individual list subscriptions below. It is set automatically when someone unsubscribes from everything, and manually via the 'Disable all emails' admin action. Per-list opt-outs do NOT change this flag. Note: subscriber analytics counts someone as 'active' when they hold at least one active list subscription, not by this flag, so the two numbers can differ."),
        ),
    ]
