# Generated by Django 6.0.6 on 2026-07-28 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_alter_historicalsubscribers_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='trial_limit',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Maximum number of clinical trials to include in a single email (default: 15). Trials that do not fit roll over to the next send.', null=True, verbose_name='Trial limit per email'),
        ),
        migrations.AddField(
            model_name='lists',
            name='trial_max_age_days',
            field=models.PositiveIntegerField(blank=True, default=90, help_text='Skip trials whose own registration or publication date is older than this. Guards against bulk imports of historical trials flooding a newsletter, because discovery_date only records when GregoryAI first saw the row. Leave blank to disable the check.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Maximum trial age (days)'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='article_limit',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Maximum number of articles to include in a single email (default: 15). Applies to weekly digest, admin summary, and trial notification emails. Articles that do not fit roll over to the next send.', null=True, verbose_name='Article limit per email'),
        ),
    ]
