# Generated by Django 6.0.6 on 2026-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0030_lists_trial_limit_lists_trial_max_age_days_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="announcementrecipient",
			name="suppressed",
			field=models.BooleanField(
				default=False,
				help_text="True when this recipient was skipped because Postmark reports them as suppressed (ErrorCode 406), not because of a delivery error. Kept separate from `success` so a suppressed recipient does not count toward the announcement's failures_count.",
			),
		),
	]
