# Generated by Django 6.0.6 on 2026-07-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0031_announcementrecipient_suppressed"),
	]

	operations = [
		migrations.AlterField(
			model_name="announcement",
			name="status",
			field=models.CharField(
				choices=[
					("draft", "Draft"),
					("queued", "Queued"),
					("sending", "Sending"),
					("sent", "Sent"),
					("failed", "Failed"),
				],
				default="draft",
				max_length=10,
			),
		),
	]
