# Generated by Django 6.0.6 on 2026-07-28 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0032_alter_announcement_status"),
	]

	operations = [
		migrations.AlterField(
			model_name="lists",
			name="lookback_days",
			field=models.PositiveIntegerField(
				default=30,
				help_text="How many days back to look for articles and trials. Applies to weekly digest, admin summary, and trial notification emails. Common values: 8, 15, 30. Maximum 365.",
				validators=[
					django.core.validators.MinValueValidator(1),
					django.core.validators.MaxValueValidator(365),
				],
				verbose_name="Lookback Window (days)",
			),
		),
	]
