# Generated by Django 6.0.6 on 2026-07-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0034_lists_article_max_age_days"),
	]

	operations = [
		migrations.CreateModel(
			name="SuppressionEvent",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"email",
					models.EmailField(
						help_text="Recipient email as reported by the triggering event; kept even when it doesn't match a Subscribers row.",
						max_length=254,
					),
				),
				(
					"record_type",
					models.CharField(
						choices=[
							(
								"SubscriptionChange",
								"Subscription Change (Postmark webhook)",
							),
							("ReactiveSendFailure", "Reactive send failure (406)"),
							("AdminManual", "Manual admin action"),
						],
						default="AdminManual",
						max_length=40,
					),
				),
				(
					"suppress_sending",
					models.BooleanField(
						default=True,
						help_text="True = a suppression event; False = an unsuppress/reactivation signal.",
					),
				),
				(
					"suppression_reason",
					models.CharField(
						blank=True,
						default="",
						help_text="Postmark SuppressionReason (HardBounce, SpamComplaint, ManualSuppression) when known; blank otherwise.",
						max_length=40,
					),
				),
				(
					"origin",
					models.CharField(
						blank=True,
						default="",
						help_text="Postmark Origin field (Recipient/Customer), recorded as data only — not used to gate reactivation (see docs/subscriptions.md).",
						max_length=20,
					),
				),
				(
					"message_stream",
					models.CharField(blank=True, default="", max_length=40),
				),
				(
					"message_id",
					models.CharField(
						blank=True,
						default="",
						help_text="Postmark MessageID. Often an all-zero placeholder for Subscription Change events — not used for idempotency.",
						max_length=64,
					),
				),
				(
					"changed_at",
					models.DateTimeField(
						help_text="Event time (Postmark ChangedAt, or local event time for reactive/admin events). Used for ordering and the reactivation staleness cap."
					),
				),
				("raw_payload", models.JSONField(blank=True, null=True)),
				(
					"deactivated_list_subscription_ids",
					models.JSONField(
						blank=True,
						default=list,
						help_text="ListSubscription IDs this event deactivated. Reactivation restores exactly this set and nothing else.",
					),
				),
				(
					"action_taken",
					models.CharField(
						choices=[
							("suppressed", "Suppressed"),
							("auto_restored", "Auto-restored"),
							("record_only", "Recorded only (not acted on)"),
						],
						default="suppressed",
						max_length=20,
					),
				),
				(
					"flag_reason",
					models.TextField(
						blank=True,
						default="",
						help_text="Why this event was recorded but not acted on automatically.",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"subscriber",
					models.ForeignKey(
						blank=True,
						help_text="Null when the recipient doesn't match any Subscribers row.",
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="suppression_events",
						to="subscriptions.subscribers",
					),
				),
			],
			options={
				"verbose_name": "Suppression Event",
				"verbose_name_plural": "Suppression Events",
				"ordering": ["-changed_at"],
			},
		),
		migrations.AddConstraint(
			model_name="suppressionevent",
			constraint=models.UniqueConstraint(
				fields=("record_type", "email", "changed_at"),
				name="unique_suppression_event_record_type_email_changed_at",
			),
		),
	]
