# Generated by Django 6.0.6 on 2026-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0035_add_suppression_event"),
	]

	operations = [
		migrations.AddIndex(
			model_name="suppressionevent",
			index=models.Index(
				fields=["email", "-changed_at"],
				name="idx_suppression_event_email_changed",
			),
		),
	]
