# Generated by Django 6.0.6 on 2026-08-19 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("subscriptions", "0036_suppression_event_email_index"),
	]

	operations = [
		migrations.AddField(
			model_name="lists",
			name="utm_campaign_slug",
			field=models.CharField(
				blank=True,
				help_text="Stable identifier used as utm_campaign in outbound email links. Set once from the list name when the list is created and never changed automatically afterwards, so renaming the list does not fork its analytics history in Umami. Changing this value manually forks the history just the same — only do it deliberately, and note the cutover date.",
				max_length=100,
				validators=[
					django.core.validators.RegexValidator(
						"^[a-z0-9_-]+$",
						"Only lowercase letters, numbers, hyphens, and underscores are allowed.",
					)
				],
				verbose_name="UTM campaign slug",
			),
		),
	]
