# Generated by Django 6.0.6 on 2026-08-20 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0038_backfill_lists_utm_campaign_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Opaque per-message id, echoed back in Postmark's Metadata field for sends that opt in. Never a resolvable person identifier.", unique=True)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', help_text="Postmark's MessageID from the send response. Blank when the send failed before Postmark returned one.", max_length=64)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('tag', models.CharField(blank=True, db_index=True, default='', help_text='Postmark Tag — the email type, e.g. weekly_summary, admin_summary, trial_notification, announcement.', max_length=40)),
                ('message_stream', models.CharField(blank=True, default='', max_length=40)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted', models.BooleanField(default=False, help_text='True when Postmark accepted the message for delivery (HTTP 200, no ErrorCode).')),
                ('error_code', models.IntegerField(blank=True, help_text='Postmark ErrorCode when not accepted.', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('complained_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_type', models.CharField(blank=True, default='', max_length=40)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='sites.site')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='subscriptions.subscribers')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Bounce', 'Bounce'), ('SpamComplaint', 'Spam Complaint'), ('Open', 'Open'), ('Click', 'Click'), ('SubscriptionChange', 'Subscription Change')], max_length=20)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text="Postmark's own event timestamp (DeliveredAt / BouncedAt / ReceivedAt / ChangedAt, depending on record_type).")),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When this webhook call was processed locally.')),
                ('tag', models.CharField(blank=True, default='', max_length=40)),
                ('message_stream', models.CharField(blank=True, default='', max_length=40)),
                ('bounce_type', models.CharField(blank=True, default='', help_text='Postmark Type.', max_length=40)),
                ('bounce_type_code', models.IntegerField(blank=True, help_text='Postmark TypeCode.', null=True)),
                ('details', models.TextField(blank=True, default='', help_text='Postmark Details. Never the message Content, which Postmark also embeds in Bounce payloads.')),
                ('link_url', models.URLField(blank=True, default='', help_text='Postmark OriginalLink — our own URL, not a tracking link.', max_length=1000)),
                ('email_message', models.ForeignKey(blank=True, help_text="Null when this event's msg_token/MessageID matched no EmailMessage row — the event is still recorded.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('record_type', 'message_id', 'occurred_at'), name='unique_email_event_type_msgid_occurred')],
            },
        ),
    ]
