# Generated by Django 6.0.6 on 2026-08-20 20:00

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0095_index_title_and_discovery_date_ordering_fields'),
        ('sites', '0002_alter_domain_unique'),
        ('subscriptions', '0039_emailmessage_emailevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorOutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label shown in the admin, e.g. 'MS Weekly — steady state' or 'MS Weekly — back catalogue'.", max_length=200)),
                ('mode', models.CharField(choices=[('upcoming', 'Upcoming (steady state — ahead of the next digest)'), ('retrospective', 'Retrospective (back catalogue — already featured)')], default='upcoming', help_text="'upcoming' (default) evaluates the same candidate set the next weekly digest will send, so the outreach email's claim 'this will be featured in the next digest' is true by construction. 'retrospective' looks at already-featured SentArticleNotification rows within featured_within_days instead, for a one-time back-catalogue send. See AUTHOR-OUTREACH-SPEC.md 'Who qualifies'.", max_length=20)),
                ('utm_campaign_slug', models.SlugField(help_text="utm_campaign value for every tracked link this campaign's emails send. Named exactly utm_campaign_slug so subscriptions.utils.utm.build_utm_params(source, campaign, content) accepts an AuthorOutreachCampaign unchanged, the same way it already accepts a Lists row. Must be distinct per campaign — the steady-state and back-catalogue campaigns on one site must never share a slug, so Umami can tell their clicks apart.", max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text="Master switch. build_author_outreach (PR 4) only writes rows for an enabled campaign. Cannot be set True unless the site's CustomSetting.has_author_pages is True — see clean().")),
                ('halted', models.BooleanField(default=False, help_text='Set by send_author_outreach (PR 5) when a safety-limit circuit breaker trips. A halted campaign sends nothing until a human clears this flag.')),
                ('halted_at', models.DateTimeField(blank=True, null=True)),
                ('halted_reason', models.TextField(blank=True, default='')),
                ('featured_within_days', models.PositiveIntegerField(default=7, help_text='retrospective mode only: how far back, from now, to look for a SentArticleNotification for the candidate article. Does nothing in upcoming mode — see clean(), which refuses a non-default value there.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('max_articles_per_email', models.PositiveIntegerField(default=3, help_text='Up to this many qualifying papers are named in one email, most recent published_date first. One email per author regardless of how many qualifying papers they have.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('subject_line', models.CharField(blank=True, default='', max_length=255)),
                ('body_template', models.TextField(blank=True, default='', help_text="Django template syntax. Blank uses the packaged default template (upcoming mode only — retrospective campaigns need their own past-tense copy and cannot use the default). Rendered (PR 5) against an explicit context of plain strings and dicts only — author_name, articles ({title, url}), article_title, article_url, author_page_url, site_name, site_url, sender_name, opt_out_url — never a model instance, so an admin-authored template can't walk the ORM.")),
                ('reply_to', models.EmailField(blank=True, default='', help_text="Reply-To header for this campaign's sends, stored per campaign so sites can differ.", max_length=254)),
                ('daily_send_limit', models.PositiveIntegerField(default=50, help_text='Stop sending for this campaign once this many messages have gone out today.', validators=[django.core.validators.MinValueValidator(1)])),
                ('send_rate_per_minute', models.PositiveIntegerField(default=20, help_text='Throttle sending to at most this many messages per minute.', validators=[django.core.validators.MinValueValidator(1)])),
                ('complaint_halt_absolute', models.PositiveIntegerField(default=2, help_text='Halt after this many total spam complaints on this campaign, regardless of volume sent.')),
                ('complaint_halt_rate_percent', models.FloatField(default=0.1, help_text='Halt when the complaint rate exceeds this percentage, once complaint_halt_rate_min_sent has been reached.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('complaint_halt_rate_min_sent', models.PositiveIntegerField(default=500, help_text='Minimum number of sends before the complaint rate threshold is evaluated.')),
                ('bounce_halt_absolute', models.PositiveIntegerField(default=10, help_text='Halt after this many total hard bounces on this campaign, regardless of volume sent.')),
                ('bounce_halt_rate_percent', models.FloatField(default=5.0, help_text='Halt when the hard-bounce rate exceeds this percentage, once bounce_halt_rate_min_sent has been reached.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('bounce_halt_rate_min_sent', models.PositiveIntegerField(default=40, help_text='Minimum number of sends before the hard-bounce rate threshold is evaluated.')),
                ('inactive_halt_absolute', models.PositiveIntegerField(default=5, help_text='Halt after this many Postmark 406 (inactive recipient) responses. Repeated 406s mean the query is repeatedly targeting already-suppressed people — a query bug, not bad luck.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='The site this campaign sends outreach for.', on_delete=django.db.models.deletion.PROTECT, related_name='author_outreach_campaigns', to='sites.site')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Restrict this campaign to weekly digest lists sharing one of these subjects. Empty means every weekly digest list on the site.', related_name='author_outreach_campaigns', to='gregory.subject')),
            ],
            options={
                'verbose_name': 'Author Outreach Campaign',
                'verbose_name_plural': 'Author Outreach Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAuthorOutreachCampaign',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label shown in the admin, e.g. 'MS Weekly — steady state' or 'MS Weekly — back catalogue'.", max_length=200)),
                ('mode', models.CharField(choices=[('upcoming', 'Upcoming (steady state — ahead of the next digest)'), ('retrospective', 'Retrospective (back catalogue — already featured)')], default='upcoming', help_text="'upcoming' (default) evaluates the same candidate set the next weekly digest will send, so the outreach email's claim 'this will be featured in the next digest' is true by construction. 'retrospective' looks at already-featured SentArticleNotification rows within featured_within_days instead, for a one-time back-catalogue send. See AUTHOR-OUTREACH-SPEC.md 'Who qualifies'.", max_length=20)),
                ('utm_campaign_slug', models.SlugField(help_text="utm_campaign value for every tracked link this campaign's emails send. Named exactly utm_campaign_slug so subscriptions.utils.utm.build_utm_params(source, campaign, content) accepts an AuthorOutreachCampaign unchanged, the same way it already accepts a Lists row. Must be distinct per campaign — the steady-state and back-catalogue campaigns on one site must never share a slug, so Umami can tell their clicks apart.", max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text="Master switch. build_author_outreach (PR 4) only writes rows for an enabled campaign. Cannot be set True unless the site's CustomSetting.has_author_pages is True — see clean().")),
                ('halted', models.BooleanField(default=False, help_text='Set by send_author_outreach (PR 5) when a safety-limit circuit breaker trips. A halted campaign sends nothing until a human clears this flag.')),
                ('halted_at', models.DateTimeField(blank=True, null=True)),
                ('halted_reason', models.TextField(blank=True, default='')),
                ('featured_within_days', models.PositiveIntegerField(default=7, help_text='retrospective mode only: how far back, from now, to look for a SentArticleNotification for the candidate article. Does nothing in upcoming mode — see clean(), which refuses a non-default value there.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('max_articles_per_email', models.PositiveIntegerField(default=3, help_text='Up to this many qualifying papers are named in one email, most recent published_date first. One email per author regardless of how many qualifying papers they have.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('subject_line', models.CharField(blank=True, default='', max_length=255)),
                ('body_template', models.TextField(blank=True, default='', help_text="Django template syntax. Blank uses the packaged default template (upcoming mode only — retrospective campaigns need their own past-tense copy and cannot use the default). Rendered (PR 5) against an explicit context of plain strings and dicts only — author_name, articles ({title, url}), article_title, article_url, author_page_url, site_name, site_url, sender_name, opt_out_url — never a model instance, so an admin-authored template can't walk the ORM.")),
                ('reply_to', models.EmailField(blank=True, default='', help_text="Reply-To header for this campaign's sends, stored per campaign so sites can differ.", max_length=254)),
                ('daily_send_limit', models.PositiveIntegerField(default=50, help_text='Stop sending for this campaign once this many messages have gone out today.', validators=[django.core.validators.MinValueValidator(1)])),
                ('send_rate_per_minute', models.PositiveIntegerField(default=20, help_text='Throttle sending to at most this many messages per minute.', validators=[django.core.validators.MinValueValidator(1)])),
                ('complaint_halt_absolute', models.PositiveIntegerField(default=2, help_text='Halt after this many total spam complaints on this campaign, regardless of volume sent.')),
                ('complaint_halt_rate_percent', models.FloatField(default=0.1, help_text='Halt when the complaint rate exceeds this percentage, once complaint_halt_rate_min_sent has been reached.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('complaint_halt_rate_min_sent', models.PositiveIntegerField(default=500, help_text='Minimum number of sends before the complaint rate threshold is evaluated.')),
                ('bounce_halt_absolute', models.PositiveIntegerField(default=10, help_text='Halt after this many total hard bounces on this campaign, regardless of volume sent.')),
                ('bounce_halt_rate_percent', models.FloatField(default=5.0, help_text='Halt when the hard-bounce rate exceeds this percentage, once bounce_halt_rate_min_sent has been reached.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('bounce_halt_rate_min_sent', models.PositiveIntegerField(default=40, help_text='Minimum number of sends before the hard-bounce rate threshold is evaluated.')),
                ('inactive_halt_absolute', models.PositiveIntegerField(default=5, help_text='Halt after this many Postmark 406 (inactive recipient) responses. Repeated 406s mean the query is repeatedly targeting already-suppressed people — a query bug, not bad luck.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='The site this campaign sends outreach for.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical Author Outreach Campaign',
                'verbose_name_plural': 'historical Author Outreach Campaigns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AuthorOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Authors.emails[0], lowercased, captured at build time — the address this row's send actually uses.", max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('legal_basis', models.CharField(choices=[('legitimate_interest', 'Legitimate interest (GDPR Art. 6(1)(f))')], default='legitimate_interest', help_text="Recorded per row, per AUTHOR-OUTREACH-SPEC.md 'Legal basis and consent': legitimate interest (GDPR Art. 6(1)(f)), with the one-time nature of the contact noted in basis_note.", max_length=30)),
                ('basis_note', models.TextField(blank=True, default='', help_text='Free-text note supporting the legal basis for this specific row, e.g. a reference to the stored balancing test.')),
                ('opt_out_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Resolves to this row in the opt-out view (PR 2). Never a resolvable person identifier on its own — see AUTHOR-OUTREACH-SPEC.md 'Non-goals'.", unique=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_author_outreach_rows', to=settings.AUTH_USER_MODEL)),
                ('articles', models.ManyToManyField(blank=True, help_text='Up to campaign.max_articles_per_email qualifying papers, most recent published_date first.', related_name='author_outreach_rows', to='gregory.articles')),
                ('author', models.ForeignKey(help_text='The author this one-time contact slot belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='outreach_rows', to='gregory.authors')),
                ('email_message', models.ForeignKey(blank=True, help_text="The EmailMessage row for this row's actual send, once sent. Named email_message, not message, for the same reason as EmailEvent's field of the same name (avoids a models.E006 clash with Django's auto-derived message_id accessor). Referenced EmailMessage rows are excluded from prune_email_messages regardless of age — see that command.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_outreach_rows', to='subscriptions.emailmessage')),
                ('site', models.ForeignKey(help_text='Denormalised from campaign.site. This, not campaign, is what unique_author_outreach_per_site constrains on, so the slot is burned per site regardless of which campaign queued it.', on_delete=django.db.models.deletion.PROTECT, related_name='author_outreach_rows', to='sites.site')),
                ('campaign', models.ForeignKey(help_text='The campaign that queued this row.', on_delete=django.db.models.deletion.PROTECT, related_name='outreach_rows', to='subscriptions.authoroutreachcampaign')),
            ],
            options={
                'verbose_name': 'Author Outreach',
                'verbose_name_plural': 'Author Outreach',
                'ordering': ['-queued_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'author'), name='unique_author_outreach_per_site')],
            },
        ),
    ]
