# Generated by Django 6.0.6 on 2026-08-20 20:33

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregory', '0095_index_title_and_discovery_date_ordering_fields'),
        ('subscriptions', '0040_authoroutreachcampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorContactOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The suppressed address, lowercased at save time. This, not author, is what every eligibility check and the unique constraint below key on — see the model docstring.', max_length=254)),
                ('reason', models.CharField(choices=[('opt_out', 'Opt-out link'), ('spam_complaint', 'Spam complaint'), ('hard_bounce', 'Hard bounce'), ('admin', 'Added manually (admin)')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='The author this address belongs to, when known. Nullable: a bounce or spam complaint carries only an address — resolving it to an Authors row is a best-effort lookup against existing AuthorOutreach rows, not something Postmark tells us directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_opt_outs', to='gregory.authors')),
            ],
            options={
                'verbose_name': 'Author Contact Opt-Out',
                'verbose_name_plural': 'Author Contact Opt-Outs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_author_optout_email')],
            },
        ),
    ]
