# Generated by Django 6.0.6 on 2026-08-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0041_authorcontactoptout'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailevent',
            name='unique_email_event_type_msgid_occurred',
        ),
        migrations.AlterField(
            model_name='emailevent',
            name='record_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Bounce', 'Bounce'), ('SpamComplaint', 'Spam Complaint'), ('Open', 'Open'), ('Click', 'Click')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='emailevent',
            constraint=models.UniqueConstraint(fields=('record_type', 'message_id', 'occurred_at', 'recipient', 'link_url'), name='unique_email_event_type_msgid_occurred_recipient_link'),
        ),
    ]
