name: Codex Issue Runner

on:
    issues:
        types: [opened, edited, reopened, labeled]

permissions:
    issues: write
    pull-requests: write

jobs:
    codex:
        if: contains(github.event.issue.labels.*.name, 'codex')
        runs-on: ubuntu-latest
        steps:
            - name: Assign issue to Codex
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      await github.issues.addAssignees({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.issue.number,
                          assignees: ['openai-codex']
                      })
            - name: Run Codex
              uses: openai/codex-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
